# Generated by Django 4.2.7 on 2023-11-21 08:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_src', models.ImageField(blank=True, null=True, upload_to='images/product')),
                ('type', models.IntegerField(choices=[(1, 'Product'), (2, 'Service')], default=1)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory_levels', models.PositiveIntegerField(blank=True, null=True)),
                ('production_output', models.PositiveIntegerField(blank=True, null=True)),
                ('demand_forecast', models.PositiveIntegerField(blank=True, null=True)),
                ('costs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('fk_business', models.ForeignKey(default=1, help_text='The business associated with the product', on_delete=django.db.models.deletion.CASCADE, related_name='fk_business_product', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_checked_for_simulation', models.BooleanField(default=False)),
                ('params', models.JSONField(blank=True, null=True)),
                ('fk_product', models.ForeignKey(default=1, help_text='The product associated with the area', on_delete=django.db.models.deletion.CASCADE, related_name='fk_product_area', to='product.product')),
            ],
        ),
    ]
