# Generated by Django 4.2.5 on 2023-10-30 23:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image_src', models.ImageField(blank=True, null=True, upload_to='images/product')),
                ('type', models.CharField(default='Dairy', max_length=50)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory_levels', models.PositiveIntegerField(blank=True, null=True)),
                ('production_output', models.PositiveIntegerField(blank=True, null=True)),
                ('demand_forecast', models.PositiveIntegerField(blank=True, null=True)),
                ('costs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('fk_business', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_business', to='business.business')),
            ],
        ),
    ]
