# Generated by Django 4.2.7 on 2023-11-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='image_src',
            field=models.ImageField(blank=True, null=True, upload_to='images/area'),
        ),
    ]
