# Generated by Django 4.2.5 on 2023-11-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[(1, 'Product'), (2, 'Service')], default=1),
        ),
    ]
