# Generated by Django 4.2.7 on 2025-05-25 23:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_options_alter_business_date_created_and_more'),
        ('product', '0002_area_image_src'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['-date_created'], 'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_created'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='area',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.TextField(help_text='Descripción detallada del área', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='area',
            name='fk_product',
            field=models.ForeignKey(help_text='El producto asociado con el área', on_delete=django.db.models.deletion.CASCADE, related_name='fk_product_area', to='product.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='area',
            name='image_src',
            field=models.ImageField(blank=True, help_text='Imagen del área (máximo 5MB, formatos: JPG, PNG)', null=True, upload_to='images/area', validators=[product.models.validate_image_size, product.models.validate_image_format], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='area',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el área está activa', verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='area',
            name='is_checked_for_simulation',
            field=models.BooleanField(default=False, help_text='Indica si el área está marcada para simulación', verbose_name='Marcada para Simulación'),
        ),
        migrations.AlterField(
            model_name='area',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(help_text='Nombre del área (máximo 100 caracteres)', max_length=100, verbose_name='Nombre del Área'),
        ),
        migrations.AlterField(
            model_name='area',
            name='params',
            field=models.JSONField(blank=True, help_text='Parámetros del área en formato JSON', null=True, verbose_name='Parámetros'),
        ),
        migrations.AlterField(
            model_name='product',
            name='costs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costos totales del producto', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='demand_forecast',
            field=models.PositiveIntegerField(blank=True, help_text='Pronóstico de demanda', null=True, verbose_name='Pronóstico de Demanda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Descripción detallada del producto', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='earnings',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ganancias totales', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ganancias'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fk_business',
            field=models.ForeignKey(help_text='El negocio asociado con el producto', on_delete=django.db.models.deletion.CASCADE, related_name='fk_business_product', to='business.business', verbose_name='Negocio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_src',
            field=models.ImageField(blank=True, help_text='Imagen del producto (máximo 5MB, formatos: JPG, PNG)', null=True, upload_to='images/product', validators=[product.models.validate_image_size, product.models.validate_image_format], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_levels',
            field=models.PositiveIntegerField(blank=True, help_text='Nivel actual de inventario', null=True, verbose_name='Nivel de Inventario'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el producto está activo', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_ready',
            field=models.BooleanField(default=False, help_text='Indica si el producto está listo para simulación', verbose_name='Listo para Simulación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Nombre del producto (máximo 100 caracteres)', max_length=100, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='production_output',
            field=models.PositiveIntegerField(blank=True, help_text='Producción estimada', null=True, verbose_name='Producción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Margen de ganancia en porcentaje (0-100%)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Margen de Ganancia (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[(1, 'Lácteos'), (2, 'Servicio')], default=1, verbose_name='Tipo de Producto'),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('name', 'fk_product')},
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['is_active', 'fk_product'], name='product_are_is_acti_4ff407_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['date_created'], name='product_are_date_cr_0d4ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'fk_business'], name='product_pro_is_acti_cda245_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['date_created'], name='product_pro_date_cr_7fa836_idx'),
        ),
    ]
