# Generated by Django 4.2.5 on 2023-11-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Product'), (2, 'Service')], default=1, null=True),
        ),
    ]
