# Generated by Django 4.2.5 on 2023-10-12 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_business_image_src_alter_business_user'),
        ('product', '0002_productcategory_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fk_category',
        ),
        migrations.AddField(
            model_name='product',
            name='fk_business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='business.business'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
