# Generated by Django 4.2.5 on 2023-10-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_fk_category_product_fk_business_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_src',
        ),
    ]
