# Generated by Django 4.2.5 on 2023-11-12 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_business_fk_user'),
        ('product', '0003_alter_product_fk_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fk_business',
            field=models.ForeignKey(default=1, help_text='The business associated with the product', on_delete=django.db.models.deletion.CASCADE, related_name='fk_business_product', to='business.business'),
        ),
    ]
