# Generated by Django 4.2.5 on 2023-10-12 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_business_image_src_alter_business_user'),
        ('product', '0004_rename_image_product_image_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fk_business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_business', to='business.business'),
        ),
    ]
