# Generated by Django 4.2.11 on 2026-04-25 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_business_type_alter_companyprofile_id_and_more'),
        ('product', '0004_product_type_multi_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fk_business',
            field=models.ForeignKey(help_text='El negocio asociado con el producto', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.business', verbose_name='Negocio'),
        ),
    ]
