# Generated by Django 4.2.5 on 2023-11-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, default='Dairy', max_length=50, null=True),
        ),
    ]
