# Generated by Django 4.2.5 on 2023-10-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productcategory_remove_product_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fk_category',
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(default='Dairy', max_length=50),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
