# Generated by Django 4.2.5 on 2023-10-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_demand_forecast_product_earnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
