# Generated by Django 4.2.5 on 2023-10-24 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_costs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_revenue',
        ),
    ]
