# Generated by Django 4.2.5 on 2023-10-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_total_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
