version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: findempro_mysql
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - findempro_network

  redis:
    image: redis:7-alpine
    container_name: findempro_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - findempro_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: findempro_backend
    restart: unless-stopped
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_ENV=production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - findempro_network

  nginx:
    image: nginx:alpine
    container_name: findempro_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static:ro
      - ./media:/app/media:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    networks:
      - findempro_network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: findempro_celery
    restart: unless-stopped
    command: celery -A findempro worker -l info
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - findempro_network

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: findempro_celery_beat
    restart: unless-stopped
    command: celery -A findempro beat -l info
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - findempro_network

volumes:
  mysql_data:
  redis_data:

networks:
  findempro_network:
    driver: bridge