version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: findempro_mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: findempro_dev
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: findempro_redis_dev
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: findempro_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: findempro_app_dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.development
    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  mysql_data_dev: