# Generated by Django 4.2.5 on 2023-10-30 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('recommendation', models.TextField()),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text='Whether the finance is active or not', verbose_name='Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date the finance was created', null=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The date the finance was last updated', null=True, verbose_name='Last Updated')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_date', models.DateField()),
                ('quantity_to_produce', models.PositiveIntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the finance is active or not', verbose_name='Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date the finance was created', null=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The date the finance was last updated', null=True, verbose_name='Last Updated')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulate.resultsimulation')),
            ],
        ),
    ]
