# Generated by Django 4.2.5 on 2023-11-19 16:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('simulate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The name of the finance', max_length=255, null=True, verbose_name='Name')),
                ('recommendation', models.TextField(blank=True, help_text='The recommendation of the finance', null=True, verbose_name='Recommendation')),
                ('description', models.TextField(blank=True, help_text='The description of the finance', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the finance is active or not', verbose_name='Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date the finance was created', null=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now_add=True, help_text='The date the finance was created', null=True, verbose_name='Date Created')),
                ('fk_business', models.ForeignKey(default=1, help_text='The business associated with the product', on_delete=django.db.models.deletion.CASCADE, related_name='fk_business_finance_recommendation', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_date', models.DateField()),
                ('quantity_to_produce', models.PositiveIntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the finance is active or not', verbose_name='Active')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('fk_finance_recommendation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_finance_recommendation_decision', to='finance.financerecommendation')),
                ('fk_result_simulation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_result_simulation_decision', to='simulate.resultsimulation')),
            ],
        ),
    ]
