# Generated by Django 4.2.7 on 2023-11-23 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecommendation',
            name='fk_business',
            field=models.ForeignKey(default=1, help_text='The business associated with the finance recomendation', on_delete=django.db.models.deletion.CASCADE, related_name='fk_business_finance_recommendation', to='business.business'),
        ),
    ]
