# Generated by Django 4.2.5 on 2023-11-11 22:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdecision',
            name='simulation',
        ),
        migrations.AddField(
            model_name='financialdecision',
            name='fk_finance_recommendation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fk_finance_recommendation', to='finance.financerecommendation'),
        ),
        migrations.AddField(
            model_name='financialdecision',
            name='fk_result_simulation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fk_result_simulation', to='simulate.resultsimulation'),
        ),
        migrations.AlterField(
            model_name='financerecommendation',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='financialdecision',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='financialdecision',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
