# Generated by Django 4.2.5 on 2023-10-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0003_rename_scenariopdf_scenariofdp_datapoint_is_active_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_date', models.DateField()),
                ('quantity_to_produce', models.PositiveIntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulate.demandsimulation')),
            ],
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Supporter',
        ),
    ]
