# Generated by Django 4.2.5 on 2023-11-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_financialdecision_simulation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecommendation',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, help_text='The date the finance was created', null=True, verbose_name='Date Created'),
        ),
    ]
