# Generated by Django 4.2.7 on 2023-12-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_financerecommendation_fk_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financerecommendation',
            name='description',
        ),
        migrations.AddField(
            model_name='financerecommendation',
            name='threshold_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The threshold value of the finance', max_digits=10, null=True, verbose_name='Threshold Value'),
        ),
        migrations.AddField(
            model_name='financerecommendation',
            name='variable_name',
            field=models.CharField(blank=True, help_text='The variable name of the finance', max_length=255, null=True, verbose_name='Variable Name'),
        ),
    ]
