# Generated by Django 4.2.5 on 2023-11-13 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0002_alter_fdp_distribution_type_and_more'),
        ('finance', '0003_alter_financerecommendation_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdecision',
            name='fk_finance_recommendation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_finance_recommendation_decision', to='finance.financerecommendation'),
        ),
        migrations.AlterField(
            model_name='financialdecision',
            name='fk_result_simulation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_result_simulation_decision', to='simulate.resultsimulation'),
        ),
    ]
