# Generated by Django 4.2.7 on 2023-12-07 21:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0012_demand_demandbehavior'),
        ('finance', '0003_remove_financerecommendation_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRecommendationSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField()),
                ('is_active', models.BooleanField(default=True, help_text='Whether the finance is active or not', verbose_name='Active')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('fk_finance_recommendation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_finance_recommendation_decision', to='finance.financerecommendation')),
                ('fk_result_simulation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_result_simulation_decision', to='simulate.resultsimulation')),
            ],
        ),
        migrations.DeleteModel(
            name='FinancialDecision',
        ),
    ]
