# Generated by Django 4.2.5 on 2023-11-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_financialdecision_fk_finance_recommendation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecommendation',
            name='description',
            field=models.TextField(blank=True, help_text='The description of the finance', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='financerecommendation',
            name='name',
            field=models.CharField(blank=True, help_text='The name of the finance', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='financerecommendation',
            name='recommendation',
            field=models.TextField(blank=True, help_text='The recommendation of the finance', null=True, verbose_name='Recommendation'),
        ),
    ]
