# Generated by Django 4.2.5 on 2023-11-19 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_business_type'),
        ('finance', '0005_alter_financerecommendation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecommendation',
            name='fk_business',
            field=models.ForeignKey(default=1, help_text='The business associated with the product', on_delete=django.db.models.deletion.CASCADE, related_name='fk_business_finance_recommendation', to='business.business'),
        ),
    ]
