# Generated by Django 4.2.11 on 2025-06-03 04:11

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("simulate", "0014_probabilisticdensityfunction_max_param_and_more"),
        ("business", "0003_remove_business_unique_business_name_per_user_and_more"),
        (
            "finance",
            "0005_remove_financerecommendationsimulation_fk_result_simulation_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financerecommendation",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "Recomendación Financiera",
                "verbose_name_plural": "Recomendaciones Financieras",
            },
        ),
        migrations.RemoveField(
            model_name="financerecommendationsimulation",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="financerecommendationsimulation",
            name="fk_finance_recommendation",
        ),
        migrations.RemoveField(
            model_name="financerecommendationsimulation",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="financerecommendationsimulation",
            name="last_updated",
        ),
        migrations.AddField(
            model_name="financerecommendation",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Descripción adicional de la recomendación",
                null=True,
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="financerecommendation",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="La fecha en que se creó la recomendación",
                null=True,
                verbose_name="Fecha de Creación",
            ),
        ),
        migrations.AlterField(
            model_name="financerecommendation",
            name="fk_business",
            field=models.ForeignKey(
                default=1,
                help_text="La empresa asociada con la recomendación financiera",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fk_business_finance_recommendation",
                to="business.business",
            ),
        ),
        migrations.AlterField(
            model_name="financerecommendation",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Si la recomendación financiera está activa o no",
                verbose_name="Activo",
            ),
        ),
        migrations.AlterField(
            model_name="financerecommendation",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="La fecha en que se actualizó la recomendación por última vez",
                null=True,
                verbose_name="Última Actualización",
            ),
        ),
        migrations.AlterField(
            model_name="financerecommendation",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="El nombre de la recomendación financiera",
                max_length=255,
                null=True,
                verbose_name="Nombre",
            ),
        ),
        migrations.AlterField(
            model_name="financerecommendation",
            name="recommendation",
            field=models.TextField(
                blank=True,
                help_text="El texto de la recomendación financiera",
                null=True,
                verbose_name="Recomendación",
            ),
        ),
        migrations.AlterField(
            model_name="financerecommendation",
            name="threshold_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="El valor umbral de la recomendación financiera",
                max_digits=10,
                null=True,
                verbose_name="Valor Umbral",
            ),
        ),
        migrations.AlterField(
            model_name="financerecommendation",
            name="variable_name",
            field=models.CharField(
                blank=True,
                help_text="El nombre de variable de la recomendación financiera",
                max_length=255,
                null=True,
                verbose_name="Nombre de Variable",
            ),
        ),
        migrations.AlterField(
            model_name="financerecommendationsimulation",
            name="data",
            field=models.FloatField(
                help_text="Datos numéricos de la simulación", verbose_name="Datos"
            ),
        ),
        migrations.AlterField(
            model_name="financerecommendationsimulation",
            name="fk_simulation",
            field=models.ForeignKey(
                help_text="Simulación asociada a la recomendación financiera",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finance_recommendation_simulations",
                to="simulate.simulation",
                verbose_name="Simulación",
            ),
        ),
        migrations.CreateModel(
            name="FinancialDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo de la decisión financiera",
                        max_length=255,
                        verbose_name="Nombre de la Decisión",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada de la decisión",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monto asociado a la decisión en la moneda local",
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Monto",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("inversion", "Inversión"),
                            ("gasto", "Gasto"),
                            ("ingreso", "Ingreso"),
                            ("financiamiento", "Financiamiento"),
                            ("ahorro", "Ahorro"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        help_text="Categoría de la decisión financiera",
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        default="media",
                        help_text="Nivel de prioridad de la decisión",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                            ("implementada", "Implementada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        help_text="Estado actual de la decisión",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "decision_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha en que se tomó la decisión",
                        null=True,
                        verbose_name="Fecha de Decisión",
                    ),
                ),
                (
                    "implementation_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha prevista o real de implementación",
                        null=True,
                        verbose_name="Fecha de Implementación",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones y notas relevantes",
                        null=True,
                        verbose_name="Notas Adicionales",
                    ),
                ),
                (
                    "expected_impact",
                    models.TextField(
                        blank=True,
                        help_text="Descripción del impacto esperado de la decisión",
                        null=True,
                        verbose_name="Impacto Esperado",
                    ),
                ),
                (
                    "risk_assessment",
                    models.TextField(
                        blank=True,
                        help_text="Análisis de riesgos asociados",
                        null=True,
                        verbose_name="Evaluación de Riesgo",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la decisión está activa",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que aprobó la decisión",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_financial_decisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó la decisión",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_financial_decisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "fk_business",
                    models.ForeignKey(
                        help_text="Empresa asociada a la decisión",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_decisions",
                        to="business.business",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decisión Financiera",
                "verbose_name_plural": "Decisiones Financieras",
                "ordering": ["-date_created"],
                "indexes": [
                    models.Index(
                        fields=["fk_business", "category"],
                        name="finance_fin_fk_busi_ae117d_idx",
                    ),
                    models.Index(
                        fields=["status", "priority"],
                        name="finance_fin_status_909b68_idx",
                    ),
                    models.Index(
                        fields=["decision_date"], name="finance_fin_decisio_ef3364_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="finance_fin_is_acti_38950f_idx"
                    ),
                ],
            },
        ),
    ]
