# Generated by Django 4.2.11 on 2025-06-25 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("simulate", "0017_remove_resultsimulation_metadata_and_more"),
        ("finance", "0006_alter_financerecommendation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financerecommendationsimulation",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "Simulación de Recomendación Financiera",
                "verbose_name_plural": "Simulaciones de Recomendaciones Financieras",
            },
        ),
        migrations.RemoveField(
            model_name="financerecommendationsimulation",
            name="data",
        ),
        migrations.AddField(
            model_name="financerecommendation",
            name="metric_value",
            field=models.FloatField(
                blank=True,
                help_text="Valor numérico asociado a la recomendación",
                null=True,
                verbose_name="Valor de Métrica",
            ),
        ),
        migrations.AddField(
            model_name="financerecommendationsimulation",
            name="actions",
            field=models.JSONField(
                default=list,
                help_text="Lista de acciones recomendadas (JSON array)",
                verbose_name="Acciones",
            ),
        ),
        migrations.AddField(
            model_name="financerecommendationsimulation",
            name="category",
            field=models.CharField(
                choices=[
                    ("critical", "Crítico"),
                    ("profitability", "Rentabilidad"),
                    ("costs", "Costos"),
                    ("efficiency", "Eficiencia"),
                    ("financial", "Financiero"),
                ],
                default="financial",
                help_text="Categoría de la recomendación",
                max_length=50,
                verbose_name="Categoría",
            ),
        ),
        migrations.AddField(
            model_name="financerecommendationsimulation",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha de Creación"
            ),
        ),
        migrations.AddField(
            model_name="financerecommendationsimulation",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Descripción detallada de la recomendación",
                null=True,
                verbose_name="Descripción",
            ),
        ),
        migrations.AddField(
            model_name="financerecommendationsimulation",
            name="impact",
            field=models.CharField(
                choices=[
                    ("low", "Bajo"),
                    ("medium", "Medio"),
                    ("high", "Alto"),
                    ("critical", "Crítico"),
                ],
                default="medium",
                help_text="Nivel de impacto de la recomendación",
                max_length=20,
                verbose_name="Impacto",
            ),
        ),
        migrations.AddField(
            model_name="financerecommendationsimulation",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AddField(
            model_name="financerecommendationsimulation",
            name="metric_value",
            field=models.FloatField(
                blank=True,
                help_text="Valor numérico asociado a la recomendación",
                null=True,
                verbose_name="Valor de Métrica",
            ),
        ),
        migrations.AddField(
            model_name="financerecommendationsimulation",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "Bajo"),
                    ("medium", "Medio"),
                    ("high", "Alto"),
                    ("critical", "Crítico"),
                ],
                default="medium",
                help_text="Nivel de severidad de la recomendación",
                max_length=20,
                verbose_name="Severidad",
            ),
        ),
        migrations.AddField(
            model_name="financerecommendationsimulation",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Título de la recomendación",
                max_length=255,
                null=True,
                verbose_name="Título",
            ),
        ),
        migrations.AlterField(
            model_name="financerecommendationsimulation",
            name="fk_simulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finance_recommendation_simulations",
                to="simulate.simulation",
                verbose_name="Simulación",
            ),
        ),
    ]
