# Generated by Django 4.2.11 on 2026-04-25 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_business_type_alter_companyprofile_id_and_more'),
        ('finance', '0008_financerecommendationsimulation_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecommendation',
            name='fk_business',
            field=models.ForeignKey(help_text='La empresa asociada con la recomendación financiera', on_delete=django.db.models.deletion.CASCADE, related_name='fk_business_finance_recommendation', to='business.business'),
        ),
    ]
