# Generated by Django 4.2.11 on 2026-05-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_merge_0009'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='financerecommendation',
            index=models.Index(fields=['fk_business', 'is_active'], name='finance_fin_fk_busi_dd97c6_idx'),
        ),
        migrations.AddIndex(
            model_name='financerecommendation',
            index=models.Index(fields=['date_created'], name='finance_fin_date_cr_f7dc8d_idx'),
        ),
    ]
