# Generated by Django 4.2.5 on 2023-10-30 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('initials', models.CharField(default='var', max_length=7)),
                ('type', models.IntegerField(default=1)),
                ('unit', models.CharField(max_length=20)),
                ('description', models.TextField(default='Descripción predeterminada')),
                ('image_src', models.ImageField(blank=True, null=True, upload_to='images/variables')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the variable is active or not', verbose_name='Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date the variable was created', null=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The date the variable was last updated', null=True, verbose_name='Last Updated')),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_product', to='product.product')),
            ],
        ),
    ]
