# Generated by Django 4.2.5 on 2023-11-19 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('expression', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text='Whether the equation is active or not', verbose_name='Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date the equation was created', null=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The date the equation was last updated', null=True, verbose_name='Last Updated')),
                ('fk_area', models.ForeignKey(help_text='The area associated with the equation', on_delete=django.db.models.deletion.CASCADE, related_name='area_equation', to='product.area')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('initials', models.CharField(default='var1', max_length=50)),
                ('type', models.IntegerField(default=1, help_text='The type of the variable')),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(default='Description predetermined')),
                ('image_src', models.ImageField(blank=True, null=True, upload_to='images/variable')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the variable is active or not', verbose_name='Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date the variable was created', null=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The date the variable was last updated', null=True, verbose_name='Last Updated')),
                ('fk_product', models.ForeignKey(default=1, help_text='The product associated with the variable', on_delete=django.db.models.deletion.CASCADE, related_name='fk_product_variable', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='EquationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the equation is active or not', verbose_name='Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date the equation result was created', verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The date the equation result was last updated', verbose_name='Last Updated')),
                ('fk_equation', models.ForeignKey(help_text='The equation associated with the result', on_delete=django.db.models.deletion.CASCADE, related_name='equation_results', to='variable.equation')),
            ],
            options={
                'verbose_name': 'Equation Result',
                'verbose_name_plural': 'Equation Results',
            },
        ),
        migrations.AddField(
            model_name='equation',
            name='fk_variable1',
            field=models.ForeignKey(help_text='The first variable associated with the equation', on_delete=django.db.models.deletion.CASCADE, related_name='fk_equations_variable1', to='variable.variable'),
        ),
        migrations.AddField(
            model_name='equation',
            name='fk_variable2',
            field=models.ForeignKey(help_text='The second variable associated with the equation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equations_variable2', to='variable.variable'),
        ),
        migrations.AddField(
            model_name='equation',
            name='fk_variable3',
            field=models.ForeignKey(help_text='The third variable associated with the equation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equations_variable3', to='variable.variable'),
        ),
        migrations.AddField(
            model_name='equation',
            name='fk_variable4',
            field=models.ForeignKey(help_text='The fourth variable associated with the equation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equations_variable4', to='variable.variable'),
        ),
        migrations.AddField(
            model_name='equation',
            name='fk_variable5',
            field=models.ForeignKey(help_text='The fifth variable associated with the equation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equations_variable5', to='variable.variable'),
        ),
    ]
