# Generated by Django 4.2.5 on 2023-11-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='description',
            field=models.TextField(default='Description predetermined'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.CharField(default='Estado', max_length=20),
        ),
    ]
