# Generated by Django 4.2.7 on 2023-11-22 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equation',
            name='fk_variable3',
            field=models.ForeignKey(blank=True, help_text='The third variable associated with the equation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equations_variable3', to='variable.variable'),
        ),
        migrations.AlterField(
            model_name='equation',
            name='fk_variable4',
            field=models.ForeignKey(blank=True, help_text='The fourth variable associated with the equation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equations_variable4', to='variable.variable'),
        ),
        migrations.AlterField(
            model_name='equation',
            name='fk_variable5',
            field=models.ForeignKey(blank=True, help_text='The fifth variable associated with the equation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equations_variable5', to='variable.variable'),
        ),
    ]
