# Generated by Django 4.2.5 on 2023-10-09 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productcategory_remove_product_quantity_and_more'),
        ('variable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=1, max_length=70, unique=True)),
                ('description', models.CharField(default='No description available.', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='variable',
            old_name='unity',
            new_name='unit',
        ),
        migrations.AddField(
            model_name='variable',
            name='fk_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='variable',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Archived')], default=1),
        ),
        migrations.AddField(
            model_name='variable',
            name='type',
            field=models.IntegerField(choices=[(1, 'Endogen'), (2, 'Exogen'), (3, 'Estado')], default=1),
        ),
        migrations.AddField(
            model_name='variable',
            name='fk_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_category', to='variable.variablecategory'),
        ),
    ]
