# Generated by Django 4.2.5 on 2023-11-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equation',
            name='expression',
            field=models.TextField(default='var1=var2+var3', help_text='The expression of the equation'),
        ),
    ]
