# Generated by Django 4.2.5 on 2023-11-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0002_alter_variable_description_alter_variable_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
