# Generated by Django 4.2.5 on 2023-10-12 23:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_fk_business'),
        ('variable', '0002_variablecategory_rename_unity_variable_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='fk_category',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='quantity',
        ),
        migrations.AddField(
            model_name='variable',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='variable',
            name='description',
            field=models.TextField(default='Descripción predeterminada'),
        ),
        migrations.AddField(
            model_name='variable',
            name='image_src',
            field=models.ImageField(blank=True, null=True, upload_to='images/variables'),
        ),
        migrations.AddField(
            model_name='variable',
            name='initials',
            field=models.CharField(default='var', max_length=7),
        ),
        migrations.AddField(
            model_name='variable',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='fk_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='product.product'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Edge',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='VariableCategory',
        ),
    ]
