# Generated by Django 4.2.7 on 2023-11-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0002_alter_equation_fk_variable3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equation',
            name='description',
            field=models.TextField(default='Description predetermined'),
        ),
    ]
