# Generated by Django 4.2.5 on 2023-11-12 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_fk_business'),
        ('variable', '0003_alter_variable_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='fk_product',
            field=models.ForeignKey(default=1, help_text='The product associated with the variable', on_delete=django.db.models.deletion.CASCADE, related_name='fk_product_variable', to='product.product'),
        ),
    ]
