# Generated by Django 4.2.7 on 2023-12-14 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0003_equation_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equationresult',
            options={},
        ),
    ]
