# Generated by Django 4.2.5 on 2023-10-12 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_fk_business'),
        ('variable', '0003_remove_variable_fk_category_remove_variable_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='fk_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_product', to='product.product'),
        ),
    ]
