# Generated by Django 4.2.7 on 2025-05-25 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_area_options_alter_product_options_and_more'),
        ('variable', '0004_alter_equationresult_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equation',
            name='fk_area',
            field=models.ForeignKey(blank=True, help_text='The area associated with the equation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_equation', to='product.area'),
        ),
        migrations.AlterField(
            model_name='equation',
            name='fk_variable2',
            field=models.ForeignKey(blank=True, help_text='The second variable associated with the equation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equations_variable2', to='variable.variable'),
        ),
        migrations.AlterField(
            model_name='equationresult',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the equation result is active or not', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.IntegerField(choices=[(1, 'Exogena'), (2, 'Estado'), (3, 'Endogena')], default=1, help_text='The type of the variable'),
        ),
    ]
