# Generated by Django 4.2.5 on 2023-10-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0004_alter_variable_fk_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='status',
        ),
        migrations.AddField(
            model_name='variable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
