# Generated by Django 4.2.5 on 2023-11-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0004_alter_variable_fk_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='parameters',
            field=models.CharField(choices=[('param1', 'Parameter 1'), ('param2', 'Parameter 2')], default='param1', max_length=20),
        ),
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.CharField(choices=[('Estado', 'Estado'), ('Exogena', 'Exogena'), ('Endogena', 'Endogena')], default='Estado', max_length=20),
        ),
    ]
