# Generated by Django 4.2.5 on 2023-11-14 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_area'),
        ('variable', '0005_variable_parameters_alter_variable_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('expression', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text='Whether the equation is active or not', verbose_name='Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date the equation was created', null=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The date the equation was last updated', null=True, verbose_name='Last Updated')),
                ('area', models.ForeignKey(help_text='The area associated with the equation', on_delete=django.db.models.deletion.CASCADE, related_name='area_equation', to='product.area')),
                ('fk_variable1', models.ForeignKey(help_text='The first variable associated with the equation', on_delete=django.db.models.deletion.CASCADE, related_name='equations_variable1', to='variable.variable')),
                ('fk_variable2', models.ForeignKey(help_text='The second variable associated with the equation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equations_variable2', to='variable.variable')),
                ('fk_variable3', models.ForeignKey(help_text='The third variable associated with the equation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equations_variable3', to='variable.variable')),
                ('fk_variable4', models.ForeignKey(help_text='The fourth variable associated with the equation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equations_variable4', to='variable.variable')),
                ('fk_variable5', models.ForeignKey(help_text='The fifth variable associated with the equation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equations_variable5', to='variable.variable')),
            ],
        ),
        migrations.CreateModel(
            name='EquationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text='Whether the equation is active or not', verbose_name='Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date the equation result was created', verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The date the equation result was last updated', verbose_name='Last Updated')),
                ('fk_equation', models.ForeignKey(help_text='The equation associated with the result', on_delete=django.db.models.deletion.CASCADE, related_name='equation_results', to='variable.equation')),
            ],
            options={
                'verbose_name': 'Equation Result',
                'verbose_name_plural': 'Equation Results',
            },
        ),
    ]
