# Generated by Django 4.2.11 on 2026-07-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "variable",
            "0005_alter_equation_fk_area_alter_equation_fk_variable2_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="equation",
            index=models.Index(
                fields=["fk_area", "is_active"], name="idx_equation_area_active"
            ),
        ),
        migrations.AddIndex(
            model_name="variable",
            index=models.Index(
                fields=["fk_product", "is_active"], name="idx_variable_prod_active"
            ),
        ),
    ]
