# Generated by Django 4.2.5 on 2023-11-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0006_equation_equationresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='image_src',
            field=models.ImageField(blank=True, null=True, upload_to='images/variable'),
        ),
    ]
