# Generated by Django 4.2.5 on 2023-11-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0007_alter_variable_image_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equation',
            old_name='area',
            new_name='fk_area',
        ),
        migrations.AlterField(
            model_name='equationresult',
            name='result',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
