# Generated by Django 4.2.5 on 2023-11-19 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0008_rename_area_equation_fk_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='parameters',
        ),
        migrations.AlterField(
            model_name='equation',
            name='fk_variable1',
            field=models.ForeignKey(help_text='The first variable associated with the equation', on_delete=django.db.models.deletion.CASCADE, related_name='fk_equations_variable1', to='variable.variable'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='initials',
            field=models.CharField(default='var1', max_length=50, unique=True),
        ),
    ]
