# Generated by Django 4.2.5 on 2023-11-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0009_remove_variable_parameters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='initials',
            field=models.CharField(default='var1', max_length=50),
        ),
    ]
