# Generated by Django 4.2.5 on 2023-11-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0011_alter_variable_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.CharField(blank=True, choices=[('Estado', 'Estado'), ('Exogena', 'Exogena'), ('Endogena', 'Endogena')], default='Exogena', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
