# Generated by Django 4.2.5 on 2023-11-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0012_alter_variable_type_alter_variable_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.CharField(choices=[('Estado', 'Estado'), ('Exogena', 'Exogena'), ('Endogena', 'Endogena')], default='Exogena', max_length=20),
        ),
    ]
