# Generated by Django 4.2.5 on 2023-11-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0013_alter_variable_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.IntegerField(choices=[(1, 'Exogena'), (2, 'Estado'), (3, 'Endogena')], default=1),
        ),
    ]
