# Generated by Django 4.2.5 on 2023-11-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0014_alter_variable_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.IntegerField(default=1, help_text='The type of the variable'),
        ),
    ]
