# Generated by Django 4.2.7 on 2025-05-25 23:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-date_created'], 'verbose_name': 'Negocio', 'verbose_name_plural': 'Negocios'},
        ),
        migrations.AlterField(
            model_name='business',
            name='date_created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='La fecha en que se creó el negocio', verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(help_text='La descripción del negocio', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='business',
            name='fk_user',
            field=models.ForeignKey(help_text='El usuario asociado con el negocio', on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='business',
            name='image_src',
            field=models.ImageField(blank=True, help_text='La imagen del negocio', null=True, upload_to='images/business/%Y/%m/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Si el negocio está activo o no', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='business',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='La fecha de la última actualización', verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.CharField(help_text='La ubicación del negocio', max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(help_text='El nombre del negocio', max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.IntegerField(choices=[(1, 'Lácteos'), (2, 'Panadería'), (3, 'Carnicería'), (4, 'Verdulería'), (5, 'Otros')], default=1, help_text='El tipo de negocio', verbose_name='Tipo'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['fk_user', 'is_active', '-date_created'], name='business_bu_fk_user_0cd217_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['type', 'is_active'], name='business_bu_type_b37dfa_idx'),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(fields=('name', 'fk_user'), name='unique_business_name_per_user'),
        ),
    ]
