# Generated by Django 4.2.5 on 2023-11-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.IntegerField(blank=True, default=1, help_text='The type of the business', null=True, verbose_name='Type'),
        ),
    ]
