# Generated by Django 4.2.11 on 2025-06-03 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "business",
            "0002_alter_business_options_alter_business_date_created_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="business",
            name="unique_business_name_per_user",
        ),
        migrations.RemoveIndex(
            model_name="business",
            name="business_bu_fk_user_0cd217_idx",
        ),
        migrations.AlterField(
            model_name="business",
            name="date_created",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="La fecha en que se creó el negocio",
                verbose_name="Fecha de Creación",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="La descripción del negocio",
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="fk_user",
            field=models.ForeignKey(
                help_text="El usuario asociado con el negocio",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="businesses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="La fecha de la última actualización",
                verbose_name="Última Actualización",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="location",
            field=models.CharField(
                db_index=True,
                help_text="La ubicación del negocio",
                max_length=255,
                verbose_name="Ubicación",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="El nombre del negocio",
                max_length=255,
                verbose_name="Nombre",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Lácteos"),
                    (2, "Agricultura"),
                    (3, "Bienes de Consumo"),
                    (4, "Panadería"),
                    (5, "Carnicería"),
                    (6, "Verdulería"),
                    (7, "Otros"),
                ],
                default=1,
                help_text="El tipo de negocio",
                verbose_name="Tipo",
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["fk_user", "is_active"], name="business_bu_fk_user_ba9240_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["location", "is_active"], name="business_bu_locatio_8fcc6a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="business",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("name", "fk_user"),
                name="unique_active_business_per_user",
            ),
        ),
    ]
