# Generated by Django 4.2.5 on 2023-10-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_rename_company_businessproduct_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
        migrations.AlterField(
            model_name='business',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='image_src',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.CharField(choices=[('LaPaz', 'La Paz'), ('Cochabamba', 'Cochabamba'), ('SantaCruz', 'Santa Cruz')], max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(choices=[('Dairy', 'Dairy')], max_length=255),
        ),
    ]
