# Generated by Django 4.2.5 on 2023-11-12 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='fk_user',
        ),
    ]
