# Generated by Django 4.2.5 on 2023-10-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_business_user_alter_business_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='business',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='business',
            name='status',
        ),
        migrations.AlterField(
            model_name='business',
            name='image_src',
            field=models.ImageField(blank=True, null=True, upload_to='business_images'),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
