# Generated by Django 4.2.5 on 2023-11-12 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0003_remove_business_fk_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='fk_user',
            field=models.ForeignKey(default=1, help_text='The user associated with the business', on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
