# Generated by Django 4.2.11 on 2026-04-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_industry_sector_companyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.IntegerField(choices=[(1, 'Lácteos'), (2, 'Agricultura'), (4, 'Panadería'), (5, 'Carnicería'), (8, 'Manufactura Alimentaria'), (9, 'Manufactura General'), (3, 'Bienes de Consumo'), (6, 'Verdulería / Minimarket'), (10, 'Retail / Comercio'), (11, 'Mayorista'), (12, 'Servicios Generales'), (13, 'Salud'), (14, 'Educación'), (15, 'Logística / Transporte'), (16, 'Hotelería / Restaurantes'), (17, 'Tecnología / Software'), (18, 'Construcción'), (19, 'Servicios Financieros'), (7, 'Otros')], default=7, help_text='El tipo/industria del negocio', verbose_name='Tipo de Industria'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='primary_cost_driver',
            field=models.CharField(default='costo_produccion', help_text='Nombre de la variable que más impacta los costos (ej: costo_produccion, costo_servicio)', max_length=100, verbose_name='Variable de Costo Principal'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='primary_revenue_driver',
            field=models.CharField(default='precio_venta', help_text='Variable que determina los ingresos (ej: precio_venta, tarifa_servicio)', max_length=100, verbose_name='Variable de Ingreso Principal'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='seasonality_factor',
            field=models.JSONField(blank=True, default=list, help_text='Lista de 12 factores mensuales [ene..dic]. Ej: [1.2, 0.9, 1.0, ...]', verbose_name='Factores de Estacionalidad'),
        ),
    ]
