# Generated by Django 4.2.5 on 2023-10-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_remove_business_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
