# Generated by Django 4.2.5 on 2023-11-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_business_fk_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.IntegerField(choices=[(1, 'Dairy'), (2, 'Exogena'), (3, 'Endogena')], default=1, help_text='The type of the business', verbose_name='Type'),
        ),
    ]
