# Generated by Django 4.2.5 on 2023-11-19 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date the business was created', verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.IntegerField(choices=[(1, 'Dairy'), (2, 'Agriculture '), (3, 'Consumer Goods')], default=1, help_text='The type of the business', verbose_name='Type'),
        ),
    ]
