# Generated by Django 4.2.5 on 2023-10-12 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0006_business_user_alter_business_image_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image_src',
            field=models.ImageField(blank=True, null=True, upload_to='images/business'),
        ),
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
