# Generated by Django 4.2.5 on 2023-10-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_business_image_src_alter_business_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='status',
        ),
        migrations.AddField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
