# Generated by Django 4.2.5 on 2023-10-24 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_remove_business_user_business_fk_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessProduct',
        ),
    ]
