# Generated by Django 4.2.7 on 2023-11-23 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_area_image_src'),
        ('questionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionary',
            name='fk_business',
        ),
        migrations.AddField(
            model_name='question',
            name='posible_answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionary',
            name='fk_product',
            field=models.ForeignKey(default=1, help_text='The product associated with the questionnaire', on_delete=django.db.models.deletion.CASCADE, related_name='fk_product_questionary', to='product.product'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='fk_question',
            field=models.ForeignKey(default=1, help_text='The question associated with the answer', on_delete=django.db.models.deletion.CASCADE, related_name='fk_question_answer', to='questionary.question'),
        ),
    ]
