# Generated by Django 4.2.5 on 2023-11-12 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_fk_user'),
        ('questionary', '0002_alter_answer_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionary',
            name='fk_business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_business_questionary', to='business.business'),
        ),
    ]
