# Generated by Django 4.2.7 on 2023-11-26 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0002_remove_questionary_fk_business_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='posible_answers',
            new_name='possible_answers',
        ),
    ]
