# Generated by Django 4.2.5 on 2023-11-21 06:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0002_answer_fk_questionary_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionaryresult',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='questionaryresult',
            name='fk_product',
        ),
        migrations.AddField(
            model_name='questionaryresult',
            name='fk_questionary',
            field=models.ForeignKey(default=1, help_text='The questionnaire associated with the question', on_delete=django.db.models.deletion.CASCADE, related_name='fk_questionary_questionary_result', to='questionary.questionary'),
        ),
        migrations.AlterField(
            model_name='questionaryresult',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date the question was created'),
        ),
        migrations.AlterField(
            model_name='questionaryresult',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date the question was last updated'),
        ),
    ]
