# Generated by Django 4.2.11 on 2026-04-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0003_rename_posible_answers_question_possible_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaryresult',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='The date the question was last updated'),
        ),
    ]
