# Generated by Django 4.2.5 on 2023-11-12 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_business_fk_user'),
        ('product', '0004_alter_product_fk_business'),
        ('questionary', '0003_questionary_fk_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='fk_questionary',
            field=models.ForeignKey(default=1, help_text='The questionnaire associated with the question', on_delete=django.db.models.deletion.CASCADE, related_name='fk_questionary_question', to='questionary.questionary'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='fk_business',
            field=models.ForeignKey(default=1, help_text='The business associated with the questionnaire', on_delete=django.db.models.deletion.CASCADE, related_name='fk_business_questionary', to='business.business'),
        ),
        migrations.AlterField(
            model_name='questionaryresult',
            name='fk_product',
            field=models.ForeignKey(help_text='The product associated with the questionnaire result', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_questionary_result_product', to='product.product'),
        ),
    ]
