# Generated by Django 4.2.11 on 2026-07-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionary", "0004_alter_questionaryresult_last_updated"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["fk_questionary_result", "is_active"],
                name="idx_answer_qresult_active",
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["fk_question", "is_active"], name="idx_answer_question_active"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["fk_questionary", "is_active"], name="idx_question_q_active"
            ),
        ),
        migrations.AddIndex(
            model_name="questionary",
            index=models.Index(
                fields=["fk_product", "is_active"], name="idx_quest_prod_active"
            ),
        ),
        migrations.AddIndex(
            model_name="questionaryresult",
            index=models.Index(
                fields=["fk_questionary", "is_active"], name="idx_questresult_q_active"
            ),
        ),
    ]
