# Generated by Django 4.2.5 on 2023-11-15 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0004_alter_question_fk_questionary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='fk_variable',
            field=models.ForeignKey(default=1, help_text='The variable associated with the question', on_delete=django.db.models.deletion.CASCADE, related_name='fk_variable_question', to='questionary.questionary'),
        ),
    ]
