# Generated by Django 4.2.5 on 2023-11-15 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0007_alter_variable_image_src'),
        ('questionary', '0006_alter_question_fk_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='fk_variable',
            field=models.ForeignKey(help_text='The variable associated with the question', on_delete=django.db.models.deletion.CASCADE, related_name='fk_variable_question', to='variable.variable'),
        ),
    ]
