# Generated by Django 4.2.5 on 2023-11-15 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0007_alter_question_fk_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='fk_questionary',
            field=models.ForeignKey(help_text='The questionnaire associated with the question', on_delete=django.db.models.deletion.CASCADE, related_name='fk_questionary_question', to='questionary.questionary'),
        ),
    ]
