# Generated by Django 4.2.5 on 2023-11-19 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0008_alter_question_fk_questionary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date the question was created'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, help_text='The status of the question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date the question was last updated'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(default=1, help_text='The type of question'),
        ),
    ]
