# Generated by Django 4.2.7 on 2025-05-25 23:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_area_options_alter_product_options_and_more'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-date_created'], 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('simulation', 'Simulación'), ('analysis', 'Análisis'), ('custom', 'Personalizado'), ('comparison', 'Comparativo')], default='simulation', max_length=20, verbose_name='Tipo de Reporte'),
        ),
        migrations.AddField(
            model_name='report',
            name='summary',
            field=models.TextField(blank=True, help_text='Resumen ejecutivo del reporte', verbose_name='Resumen'),
        ),
        migrations.AddField(
            model_name='report',
            name='tags',
            field=models.CharField(blank=True, help_text='Etiquetas separadas por comas', max_length=500, verbose_name='Etiquetas'),
        ),
        migrations.AddField(
            model_name='report',
            name='version',
            field=models.CharField(default='1.0', max_length=10, verbose_name='Versión'),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.JSONField(default=dict, help_text='Contenido del reporte en formato JSON', verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='report',
            name='fk_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='product.product', verbose_name='Producto Asociado'),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el reporte está activo', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(help_text='Título descriptivo del reporte', max_length=200, verbose_name='Título'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['-date_created'], name='report_repo_date_cr_99ef2e_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_active'], name='report_repo_is_acti_ef8063_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='report_repo_report__00de4f_idx'),
        ),
        migrations.AlterModelTable(
            name='report',
            table='report_report',
        ),
    ]
