# Generated by Django 4.2.5 on 2023-10-30 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_config', models.JSONField(default=dict, help_text='Structured JSON data for widget configuration.')),
                ('layout_config', models.JSONField(default=dict, help_text='Structured JSON data for layout configuration.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the business is active or not', verbose_name='Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date the business was created', null=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The date the business was last updated', null=True, verbose_name='Last Updated')),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_product_dashboard', to='product.product')),
            ],
        ),
    ]
