# Generated by Django 4.2.7 on 2023-11-27 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_area_image_src'),
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Chart', help_text='The title of the chart.', max_length=255)),
                ('chart_type', models.CharField(default='line', help_text='The type of chart to use.', max_length=50)),
                ('chart_data', models.JSONField(default=list, help_text='Structured JSON data for chart configuration.')),
                ('widget_config', models.JSONField(default=dict, help_text='Structured JSON data for widget configuration.')),
                ('layout_config', models.JSONField(default=dict, help_text='Structured JSON data for layout configuration.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the chart is active or not', verbose_name='Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date the chart was created', null=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The date the chart was last updated', null=True, verbose_name='Last Updated')),
                ('fk_product', models.ForeignKey(default=1, help_text='The product associated with the chart.', on_delete=django.db.models.deletion.CASCADE, related_name='fk_product_charts', to='product.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
