# Generated by Django 4.2.5 on 2023-11-12 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='product',
            new_name='fk_product',
        ),
    ]
