# Generated by Django 4.2.5 on 2023-11-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='quantity',
            field=models.IntegerField(default=0, help_text='The quantity of the demand'),
        ),
    ]
