# Generated by Django 4.2.5 on 2023-11-14 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_area'),
        ('dashboards', '0002_rename_product_dashboard_fk_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the business is active or not', verbose_name='Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date the business was created', null=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The date the business was last updated', null=True, verbose_name='Last Updated')),
                ('fk_product', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_demand_product', to='product.product')),
            ],
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date the dashboard was created', null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='fk_product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_product_dashboard', to='product.product'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the dashboard is active or not', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='The date the dashboard was last updated', null=True, verbose_name='Last Updated'),
        ),
        migrations.CreateModel(
            name='DemandBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the business is active or not', verbose_name='Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date the business was created', null=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The date the business was last updated', null=True, verbose_name='Last Updated')),
                ('fk_demand', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_demand_behavior_demand', to='dashboards.demand')),
            ],
        ),
    ]
