# Generated by Django 4.2.5 on 2023-11-18 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_area'),
        ('dashboards', '0003_demand_alter_dashboard_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='fk_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fk_product_dashboard', to='product.product'),
        ),
    ]
