# Generated by Django 4.2.7 on 2023-12-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_remove_demandbehavior_current_demand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='chart_image',
            field=models.ImageField(blank=True, help_text='Chart image', null=True, upload_to='chart_images/'),
        ),
    ]
