# Generated by Django 4.2.5 on 2023-11-18 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_area'),
        ('dashboards', '0004_alter_dashboard_fk_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandbehavior',
            name='fk_demand',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='chart_data',
            field=models.JSONField(default=dict, help_text='Structured JSON data for chart configuration.'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='chart_type',
            field=models.CharField(default='line', help_text='The type of chart to use for the dashboard.', max_length=50),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='title',
            field=models.CharField(default='Dashboard', help_text='The title of the dashboard.', max_length=255),
        ),
        migrations.AddField(
            model_name='demand',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='demandbehavior',
            name='current_demand',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_demand_behavior_current_demand', to='dashboards.demand'),
        ),
        migrations.AddField(
            model_name='demandbehavior',
            name='predicted_demand',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_demand_behavior_predicted_demand', to='dashboards.demand'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='fk_product',
            field=models.ForeignKey(default=1, help_text='The product associated with the dashboard.', on_delete=django.db.models.deletion.CASCADE, related_name='fk_product_dashboard', to='product.product'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='fk_product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_product_demand', to='product.product'),
        ),
    ]
