# Generated by Django 4.2.7 on 2025-05-25 23:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_area_options_alter_product_options_and_more'),
        ('dashboards', '0005_chart_chart_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la plantilla', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción de la plantilla')),
                ('chart_type', models.CharField(choices=[('line', 'Línea'), ('bar', 'Barras'), ('pie', 'Circular'), ('donut', 'Dona'), ('area', 'Área'), ('scatter', 'Dispersión'), ('heatmap', 'Mapa de calor'), ('candlestick', 'Velas')], help_text='Tipo de gráfico de la plantilla', max_length=50)),
                ('default_config', models.JSONField(default=dict, help_text='Configuración por defecto de la plantilla')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la plantilla está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Gráfico',
                'verbose_name_plural': 'Plantillas de Gráficos',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='chart',
            options={'ordering': ['-render_priority', '-date_created'], 'verbose_name': 'Gráfico', 'verbose_name_plural': 'Gráficos'},
        ),
        migrations.AddField(
            model_name='chart',
            name='cache_key',
            field=models.CharField(blank=True, help_text='Clave de caché para el gráfico', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='render_priority',
            field=models.IntegerField(default=0, help_text='Prioridad de renderizado (mayor = más prioritario)'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='chart_data',
            field=models.JSONField(default=dict, help_text='Datos del gráfico en formato JSON'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='chart_image',
            field=models.ImageField(blank=True, help_text='Imagen renderizada del gráfico', null=True, upload_to='chart_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='chart',
            name='chart_type',
            field=models.CharField(choices=[('line', 'Línea'), ('bar', 'Barras'), ('pie', 'Circular'), ('donut', 'Dona'), ('area', 'Área'), ('scatter', 'Dispersión'), ('heatmap', 'Mapa de calor'), ('candlestick', 'Velas')], default='line', help_text='Tipo de visualización del gráfico', max_length=50),
        ),
        migrations.AlterField(
            model_name='chart',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='fk_product',
            field=models.ForeignKey(help_text='Producto asociado al gráfico', on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='product.product'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el gráfico está activo', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='layout_config',
            field=models.JSONField(default=dict, help_text='Configuración de diseño del gráfico'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='title',
            field=models.CharField(help_text='Título descriptivo del gráfico', max_length=255, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='chart',
            name='widget_config',
            field=models.JSONField(default=dict, help_text='Configuración del widget (tamaño, colores, etc.)'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['fk_product', 'is_active'], name='dashboards__fk_prod_91dd9e_idx'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['chart_type', 'is_active'], name='dashboards__chart_t_832b82_idx'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['-date_created'], name='dashboards__date_cr_5928ad_idx'),
        ),
    ]
