# Generated by Django 4.2.5 on 2023-11-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_demand_fk_result_simulation_demand_is_predicted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='chart_type',
            field=models.CharField(blank=True, default='line', help_text='The type of chart to use for the dashboard.', max_length=50, null=True),
        ),
    ]
