# Generated by Django 4.2.5 on 2023-11-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_alter_dashboard_chart_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='chart_type',
            field=models.CharField(default='line', help_text='The type of chart to use for the dashboard.', max_length=50),
        ),
    ]
