# Generated by Django 4.2.11 on 2025-06-05 22:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructions',
            options={'ordering': ['order', 'type', 'date_created'], 'verbose_name': 'Instrucción', 'verbose_name_plural': 'Instrucciones'},
        ),
        migrations.AddField(
            model_name='instructions',
            name='order',
            field=models.IntegerField(default=0, help_text='Orden de visualización de las instrucciones', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='content',
            field=models.TextField(blank=True, help_text='Contenido detallado de las instrucciones', null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='La fecha en que se crearon las instrucciones', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='fk_user',
            field=models.ForeignKey(help_text='El usuario asociado con las instrucciones', on_delete=django.db.models.deletion.CASCADE, related_name='user_instructions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='instruction',
            field=models.TextField(blank=True, help_text='Título o resumen de la instrucción', null=True, verbose_name='Instrucción'),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si las instrucciones están activas o no', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='La fecha de la última actualización', verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='type',
            field=models.IntegerField(choices=[(1, 'General'), (2, 'Financiera'), (3, 'Técnica'), (4, 'Operativa')], default=1, help_text='El tipo de instrucción', verbose_name='Tipo'),
        ),
        migrations.AddIndex(
            model_name='instructions',
            index=models.Index(fields=['fk_user', 'is_active'], name='pages_instr_fk_user_8bbcfd_idx'),
        ),
        migrations.AddIndex(
            model_name='instructions',
            index=models.Index(fields=['type', 'order'], name='pages_instr_type_0fde88_idx'),
        ),
    ]
