# Generated by Django 4.2.5 on 2023-10-30 23:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('questionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('distribution_type', models.CharField(choices=[('normal', 'Normal'), ('exponential', 'Exponential'), ('logarithmic', 'Logarithmic')], default='normal', max_length=20)),
                ('lambda_param', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utime', models.CharField(max_length=100)),
                ('date_simulate', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('fk_fdp', models.ManyToManyField(default=1, related_name='fk_fdp_simulation', to='simulate.fdp')),
                ('fk_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_product_simulation', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioFDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('fdp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulate.fdp')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulate.simulationscenario')),
            ],
        ),
        migrations.CreateModel(
            name='ResultSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_date', models.DateField()),
                ('demand_mean', models.DecimalField(decimal_places=2, max_digits=10)),
                ('demand_std_deviation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('fk_questionary_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_questionary_result', to='questionary.questionaryresult')),
                ('fk_simulation_scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_simulations', to='simulate.simulationscenario')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
