# Generated by Django 4.2.7 on 2023-11-23 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='fk_fdp',
            field=models.ForeignKey(blank=True, default=None, help_text='The probabilistic density function associated with the simulation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_fdp_simulation', to='simulate.probabilisticdensityfunction'),
        ),
    ]
