# Generated by Django 4.2.5 on 2023-11-12 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdp',
            name='distribution_type',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Exponential'), (3, 'Logarithmic')], default=1),
        ),
        migrations.AlterField(
            model_name='resultsimulation',
            name='fk_simulation_scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_simulation_scenario_result_simulation', to='simulate.simulationscenario'),
        ),
    ]
