# Generated by Django 4.2.5 on 2023-11-20 22:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0002_answer_fk_questionary_result_and_more'),
        ('product', '0004_alter_product_type'),
        ('simulate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationscenario',
            name='fk_fdp',
        ),
        migrations.RemoveField(
            model_name='simulationscenario',
            name='fk_product',
        ),
        migrations.AlterModelOptions(
            name='simulation',
            options={},
        ),
        migrations.RemoveField(
            model_name='resultsimulation',
            name='fk_questionary_result',
        ),
        migrations.RemoveField(
            model_name='resultsimulation',
            name='fk_simulation_scenario',
        ),
        migrations.RemoveField(
            model_name='resultsimulation',
            name='simulation_date',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='product',
        ),
        migrations.AddField(
            model_name='resultsimulation',
            name='fk_simulation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_simulation_result_simulation', to='simulate.simulation'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='simulation',
            name='fk_fdp',
            field=models.ManyToManyField(default=1, related_name='fk_fdp_simulation', to='simulate.fdp'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='fk_questionary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_product_simulation', to='questionary.questionary'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='unit_time',
            field=models.CharField(default='day', help_text='The unit of time for the simulation', max_length=100),
        ),
        migrations.AddField(
            model_name='simulation',
            name='weight',
            field=models.FloatField(default=1, help_text='The weight of the simulation'),
        ),
        migrations.AlterField(
            model_name='resultsimulation',
            name='demand_mean',
            field=models.DecimalField(decimal_places=2, help_text='The mean of the demand', max_digits=10),
        ),
        migrations.AlterField(
            model_name='resultsimulation',
            name='demand_std_deviation',
            field=models.DecimalField(decimal_places=2, help_text='The standard deviation of the demand', max_digits=10),
        ),
        migrations.AlterField(
            model_name='resultsimulation',
            name='product',
            field=models.ForeignKey(help_text='The product associated with the result', on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='distributions',
            field=models.ManyToManyField(help_text='The FDPs associated with the simulation', related_name='simulations', to='simulate.fdp'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='questionary_result',
            field=models.ForeignKey(help_text='The questionary result associated with the simulation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='questionary.questionaryresult'),
        ),
        migrations.DeleteModel(
            name='ScenarioFDP',
        ),
        migrations.DeleteModel(
            name='SimulationScenario',
        ),
    ]
