# Generated by Django 4.2.5 on 2023-10-09 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productcategory_remove_product_quantity_and_more'),
        ('simulate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExponentialFDP',
            fields=[
                ('fdp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulate.fdp')),
            ],
            bases=('simulate.fdp',),
        ),
        migrations.CreateModel(
            name='LogarithmicFDP',
            fields=[
                ('fdp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulate.fdp')),
            ],
            bases=('simulate.fdp',),
        ),
        migrations.CreateModel(
            name='NormalFDP',
            fields=[
                ('fdp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulate.fdp')),
                ('mean', models.FloatField()),
                ('std_deviation', models.FloatField()),
            ],
            bases=('simulate.fdp',),
        ),
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utime', models.CharField(max_length=100)),
                ('date_simulate', models.DateField()),
                ('fdps', models.ManyToManyField(to='simulate.fdp')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('fdp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulate.fdp')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulate.simulationscenario')),
            ],
        ),
    ]
