# Generated by Django 4.2.7 on 2023-11-27 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0002_alter_simulation_fk_fdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='fk_fdp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='simulate.probabilisticdensityfunction'),
        ),
    ]
