# Generated by Django 4.2.5 on 2023-11-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0002_remove_simulationscenario_fk_fdp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_time', models.IntegerField()),
                ('demand', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='FDP',
            new_name='ProbabilisticDensityFunction',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='demand_mean',
        ),
        migrations.AddField(
            model_name='resultsimulation',
            name='date',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultsimulation',
            name='results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultsimulation',
            name='unit',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultsimulation',
            name='unit_time',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultsimulation',
            name='variables',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='demand_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='distributions',
            field=models.ManyToManyField(help_text='The ProbabilisticDensityFunctions associated with the simulation', related_name='simulations', to='simulate.fdp'),
        ),
    ]
