# Generated by Django 4.2.5 on 2023-10-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productcategory_remove_product_status_and_more'),
        ('question', '0001_initial'),
        ('simulate', '0002_exponentialfdp_logarithmicfdp_normalfdp_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScenarioPDF',
            new_name='ScenarioFDP',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fdp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='simulationscenario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DemandSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_date', models.DateField()),
                ('demand_mean', models.DecimalField(decimal_places=2, max_digits=10)),
                ('demand_std_deviation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_questionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_questionary', to='question.question')),
                ('fk_simulation_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_simulation_scenario', to='simulate.simulationscenario')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
