# Generated by Django 4.2.5 on 2023-11-19 05:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0008_alter_question_fk_questionary'),
        ('product', '0005_area'),
        ('simulate', '0002_alter_fdp_distribution_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('demand_mean', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('distributions', models.ManyToManyField(related_name='simulations', to='simulate.fdp')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='product.product')),
                ('questionary_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='questionary.questionaryresult')),
            ],
            options={
                'verbose_name': 'Simulation',
                'ordering': ['-date'],
            },
        ),
    ]
