# Generated by Django 4.2.7 on 2023-11-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0003_alter_simulation_fk_fdp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandhistorical',
            name='unit_time',
        ),
        migrations.AddField(
            model_name='simulation',
            name='quantity_time',
            field=models.IntegerField(default=1, help_text='The quantity of the simulation'),
        ),
    ]
