# Generated by Django 4.2.7 on 2023-11-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0004_remove_demandhistorical_unit_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='probabilisticdensityfunction',
            name='mean_param',
            field=models.FloatField(blank=True, help_text='Mean parameter for the normal distribution', null=True),
        ),
    ]
