# Generated by Django 4.2.7 on 2023-11-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0004_alter_simulation_distributions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandHistorical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_time', models.IntegerField()),
                ('demand', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricalDemand',
        ),
    ]
