# Generated by Django 4.2.7 on 2023-11-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0005_probabilisticdensityfunction_mean_param'),
    ]

    operations = [
        migrations.AddField(
            model_name='probabilisticdensityfunction',
            name='std_dev_param',
            field=models.FloatField(blank=True, help_text='Standard deviation parameter for the normal distribution', null=True),
        ),
    ]
