# Generated by Django 4.2.7 on 2023-11-29 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('simulate', '0007_remove_resultsimulation_results_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataPoint',
        ),
        migrations.AddField(
            model_name='probabilisticdensityfunction',
            name='fk_business',
            field=models.ForeignKey(default=1, help_text='The business associated with the fdp', on_delete=django.db.models.deletion.CASCADE, related_name='fk_business_fdp', to='business.business'),
        ),
    ]
