# Generated by Django 4.2.7 on 2023-11-29 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0008_delete_datapoint_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemandHistorical',
        ),
    ]
