# Generated by Django 4.2.7 on 2023-11-29 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0009_delete_demandhistorical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probabilisticdensityfunction',
            name='fk_business',
        ),
    ]
