# Generated by Django 4.2.7 on 2023-11-30 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_area_image_src'),
        ('simulate', '0011_probabilisticdensityfunction_fk_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='The quantity of the demand')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the business is active or not', verbose_name='Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date the business was created', null=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The date the business was last updated', null=True, verbose_name='Last Updated')),
                ('is_predicted', models.BooleanField(default=False, help_text='Whether the demand is predicted or not', verbose_name='Predicted')),
                ('fk_product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_product_demand_behavior', to='product.product')),
                ('fk_simulation', models.ForeignKey(default=1, help_text='The result simulation associated with the demand', on_delete=django.db.models.deletion.CASCADE, related_name='fk_result_simulation_demand', to='simulate.simulation', verbose_name='Result Simulation')),
            ],
        ),
        migrations.CreateModel(
            name='DemandBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the business is active or not', verbose_name='Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date the business was created', null=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The date the business was last updated', null=True, verbose_name='Last Updated')),
                ('current_demand', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_demand_behavior_current_demand', to='simulate.demand')),
                ('predicted_demand', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_demand_behavior_predicted_demand', to='simulate.demand')),
            ],
        ),
    ]
