# Generated by Django 4.2.7 on 2025-05-25 23:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_area_options_alter_product_options_and_more'),
        ('business', '0002_alter_business_options_alter_business_date_created_and_more'),
        ('questionary', '0003_rename_posible_answers_question_possible_answers'),
        ('simulate', '0012_demand_demandbehavior'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demand',
            options={'ordering': ['-date_created'], 'verbose_name': 'Demand', 'verbose_name_plural': 'Demands'},
        ),
        migrations.AlterModelOptions(
            name='demandbehavior',
            options={'verbose_name': 'Demand Behavior', 'verbose_name_plural': 'Demand Behaviors'},
        ),
        migrations.AlterModelOptions(
            name='probabilisticdensityfunction',
            options={'ordering': ['-date_created'], 'verbose_name': 'Probability Density Function', 'verbose_name_plural': 'Probability Density Functions'},
        ),
        migrations.AlterModelOptions(
            name='resultsimulation',
            options={'ordering': ['fk_simulation', 'date'], 'verbose_name': 'Simulation Result', 'verbose_name_plural': 'Simulation Results'},
        ),
        migrations.AlterModelOptions(
            name='simulation',
            options={'ordering': ['-date_created'], 'verbose_name': 'Simulation', 'verbose_name_plural': 'Simulations'},
        ),
        migrations.AddField(
            model_name='demand',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='Confidence score for predictions', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='demandbehavior',
            name='elasticity_coefficient',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Calculated elasticity coefficient', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='demandbehavior',
            name='elasticity_type',
            field=models.CharField(choices=[('elastic', 'Elastic'), ('inelastic', 'Inelastic'), ('neutral', 'Neutral'), ('unknown', 'Unknown')], default='unknown', help_text='Type of demand elasticity', max_length=20),
        ),
        migrations.AddField(
            model_name='demandbehavior',
            name='percentage_change',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Percentage change in demand', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='resultsimulation',
            name='confidence_intervals',
            field=models.JSONField(blank=True, default=dict, help_text='Confidence intervals for key metrics'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='confidence_level',
            field=models.FloatField(default=0.95, help_text='Confidence level for statistical analysis', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.AddField(
            model_name='simulation',
            name='random_seed',
            field=models.IntegerField(blank=True, help_text='Random seed for reproducible results', null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='demand',
            name='fk_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='product.product'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='fk_simulation',
            field=models.ForeignKey(help_text='Associated simulation', on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='simulate.simulation'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='is_predicted',
            field=models.BooleanField(default=False, help_text='Whether this is a predicted value'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Demand quantity', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='demandbehavior',
            name='current_demand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_behavior', to='simulate.demand'),
        ),
        migrations.AlterField(
            model_name='demandbehavior',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='demandbehavior',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='demandbehavior',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='demandbehavior',
            name='predicted_demand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_behavior', to='simulate.demand'),
        ),
        migrations.AlterField(
            model_name='probabilisticdensityfunction',
            name='cumulative_distribution_function',
            field=models.FloatField(blank=True, help_text='Cumulative distribution function value', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='probabilisticdensityfunction',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date'),
        ),
        migrations.AlterField(
            model_name='probabilisticdensityfunction',
            name='distribution_type',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Exponential'), (3, 'Log-Norm')], default=1, help_text='The type of the distribution'),
        ),
        migrations.AlterField(
            model_name='probabilisticdensityfunction',
            name='fk_business',
            field=models.ForeignKey(help_text='The business associated with this distribution', on_delete=django.db.models.deletion.CASCADE, related_name='probability_distributions', to='business.business'),
        ),
        migrations.AlterField(
            model_name='probabilisticdensityfunction',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the distribution is active'),
        ),
        migrations.AlterField(
            model_name='probabilisticdensityfunction',
            name='lambda_param',
            field=models.FloatField(blank=True, help_text='Lambda parameter for exponential distribution', null=True, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='probabilisticdensityfunction',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last update date'),
        ),
        migrations.AlterField(
            model_name='probabilisticdensityfunction',
            name='mean_param',
            field=models.FloatField(blank=True, help_text='Mean parameter for normal distribution', null=True),
        ),
        migrations.AlterField(
            model_name='probabilisticdensityfunction',
            name='name',
            field=models.CharField(default='Distribution', help_text='The name of the distribution', max_length=100),
        ),
        migrations.AlterField(
            model_name='probabilisticdensityfunction',
            name='std_dev_param',
            field=models.FloatField(blank=True, help_text='Standard deviation parameter', null=True, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='resultsimulation',
            name='areas',
            field=models.JSONField(blank=True, default=dict, help_text='Area-specific results'),
        ),
        migrations.AlterField(
            model_name='resultsimulation',
            name='date',
            field=models.DateField(help_text='Date of this simulation result'),
        ),
        migrations.AlterField(
            model_name='resultsimulation',
            name='demand_mean',
            field=models.DecimalField(decimal_places=4, help_text='Mean demand for this day', max_digits=12),
        ),
        migrations.AlterField(
            model_name='resultsimulation',
            name='demand_std_deviation',
            field=models.DecimalField(decimal_places=4, help_text='Standard deviation of demand', max_digits=12),
        ),
        migrations.AlterField(
            model_name='resultsimulation',
            name='fk_simulation',
            field=models.ForeignKey(help_text='Parent simulation', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='simulate.simulation'),
        ),
        migrations.AlterField(
            model_name='resultsimulation',
            name='variables',
            field=models.JSONField(default=dict, help_text='Variable values for this day'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='demand_history',
            field=models.JSONField(help_text='Historical demand data (JSON array of numbers)'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='fk_fdp',
            field=models.ForeignKey(help_text='Probability distribution function used', on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='simulate.probabilisticdensityfunction'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='fk_questionary_result',
            field=models.ForeignKey(help_text='Associated questionary result', on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='questionary.questionaryresult'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='quantity_time',
            field=models.PositiveIntegerField(default=1, help_text='Number of time units for simulation', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='unit_time',
            field=models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='days', help_text='Unit of time for simulation', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='probabilisticdensityfunction',
            unique_together={('distribution_type', 'fk_business')},
        ),
        migrations.AlterUniqueTogether(
            name='resultsimulation',
            unique_together={('fk_simulation', 'date')},
        ),
    ]
