# Generated by Django 4.2.11 on 2025-06-03 04:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulate", "0013_alter_demand_options_alter_demandbehavior_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="probabilisticdensityfunction",
            name="max_param",
            field=models.FloatField(
                blank=True,
                help_text="Maximum value for uniform distribution",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="probabilisticdensityfunction",
            name="min_param",
            field=models.FloatField(
                blank=True,
                help_text="Minimum value for uniform distribution",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="probabilisticdensityfunction",
            name="scale_param",
            field=models.FloatField(
                blank=True,
                help_text="Scale parameter (β) for gamma distribution",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.001)],
            ),
        ),
        migrations.AddField(
            model_name="probabilisticdensityfunction",
            name="shape_param",
            field=models.FloatField(
                blank=True,
                help_text="Shape parameter (α) for gamma distribution",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.001)],
            ),
        ),
        migrations.AlterField(
            model_name="probabilisticdensityfunction",
            name="distribution_type",
            field=models.IntegerField(
                choices=[
                    (1, "Normal"),
                    (2, "Exponential"),
                    (3, "Log-Norm"),
                    (4, "Gamma"),
                    (5, "Uniform"),
                ],
                default=1,
                help_text="The type of the distribution",
            ),
        ),
    ]
