# Generated by Django 4.2.11 on 2025-06-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulate", "0014_probabilisticdensityfunction_max_param_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="completion_date",
            field=models.DateTimeField(
                blank=True, help_text="Fecha de finalización", null=True
            ),
        ),
        migrations.AddField(
            model_name="simulation",
            name="demand_config",
            field=models.TextField(
                blank=True,
                help_text="Configuración de demanda en formato JSON",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="simulation",
            name="execution_report",
            field=models.TextField(
                blank=True, help_text="Reporte de ejecución de simulación", null=True
            ),
        ),
        migrations.AddField(
            model_name="simulation",
            name="extracted_variables",
            field=models.TextField(
                blank=True,
                help_text="Variables extraídas desde BD en formato JSON",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="simulation",
            name="extraction_report",
            field=models.TextField(
                blank=True, help_text="Reporte de extracción de variables", null=True
            ),
        ),
        migrations.AddField(
            model_name="simulation",
            name="is_completed",
            field=models.BooleanField(
                default=False, help_text="Indica si la simulación se completó"
            ),
        ),
    ]
