# Generated by Django 4.2.11 on 2025-06-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "simulate",
            "0015_simulation_completion_date_simulation_demand_config_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="resultsimulation",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Metadatos del resultado"
            ),
        ),
    ]
