# Generated by Django 4.2.11 on 2026-04-30 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulate', '0017_remove_resultsimulation_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfacePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('page_order', models.IntegerField(default=0)),
                ('background_color', models.CharField(default='#0f172a', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['page_order'],
            },
        ),
        migrations.CreateModel(
            name='SimulationProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('domain', models.CharField(choices=[('dairy', 'Sector Lácteo'), ('agro', 'Agroindustrial'), ('retail', 'Retail'), ('services', 'Servicios'), ('manufacturing', 'Manufactura'), ('generic', 'Genérico')], default='dairy', max_length=50)),
                ('run_specs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canvas_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('stock', 'Stock'), ('flow', 'Flow'), ('converter', 'Converter'), ('connector', 'Connector'), ('ghost', 'Ghost'), ('text_box', 'Text Box')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('equation', models.TextField(blank=True, null=True)),
                ('initial_value', models.FloatField(blank=True, null=True)),
                ('units', models.CharField(blank=True, max_length=50)),
                ('position_x', models.FloatField(default=100.0)),
                ('position_y', models.FloatField(default=100.0)),
                ('width', models.FloatField(default=120.0)),
                ('height', models.FloatField(default=60.0)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('distribution_config', models.JSONField(blank=True, help_text='Config de distribución: {dist_type, params}', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ghost_of_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ghost_instances', to='simulate.modelnode')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='simulate.simulationproject')),
            ],
        ),
        migrations.CreateModel(
            name='ModelEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_type', models.CharField(choices=[('causal', 'Causal'), ('flow', 'Flow'), ('info', 'Info')], default='causal', max_length=20)),
                ('line_style', models.CharField(choices=[('solid', 'Sólido'), ('dashed', 'Punteado')], default='solid', max_length=20)),
                ('polarity', models.CharField(blank=True, max_length=5, null=True)),
                ('waypoints', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='simulate.simulationproject')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='simulate.modelnode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='simulate.modelnode')),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_type', models.CharField(choices=[('slider', 'Slider'), ('knob', 'Knob'), ('dial', 'Dial'), ('run_button', 'Run Button'), ('stop_button', 'Stop Button'), ('reset_button', 'Reset Button'), ('time_slider', 'Time Slider'), ('graph_output', 'Graph Output'), ('table_output', 'Table Output'), ('gauge', 'Gauge'), ('numeric_display', 'Numeric Display'), ('scenario_toggle', 'Scenario Toggle'), ('text_annotation', 'Text Annotation'), ('page_nav', 'Page Navigation')], max_length=30)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('linked_variable', models.CharField(blank=True, max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('position_x', models.FloatField(default=50.0)),
                ('position_y', models.FloatField(default=50.0)),
                ('width', models.FloatField(default=200.0)),
                ('height', models.FloatField(default=100.0)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('linked_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulate.modelnode')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='simulate.interfacepage')),
            ],
        ),
        migrations.AddField(
            model_name='interfacepage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='simulate.simulationproject'),
        ),
        migrations.CreateModel(
            name='CanvasSimulationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_type', models.CharField(choices=[('montecarlo', 'Monte Carlo'), ('des', 'Discrete Event Simulation'), ('sensitivity', 'Sensitivity Analysis'), ('scenario', 'Scenario')], default='montecarlo', max_length=20)),
                ('parameters_snapshot', models.JSONField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, null=True)),
                ('statistics', models.JSONField(blank=True, null=True)),
                ('run_duration_ms', models.IntegerField(blank=True, null=True)),
                ('n_runs', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='simulate.simulationproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='modelnode',
            index=models.Index(fields=['project'], name='simulate_mo_project_91b0d9_idx'),
        ),
        migrations.AddIndex(
            model_name='modeledge',
            index=models.Index(fields=['project'], name='simulate_mo_project_2f6e30_idx'),
        ),
        migrations.AddIndex(
            model_name='interfacewidget',
            index=models.Index(fields=['page'], name='simulate_in_page_id_47e82c_idx'),
        ),
        migrations.AddIndex(
            model_name='canvassimulationrun',
            index=models.Index(fields=['project', '-created_at'], name='simulate_ca_project_ea0944_idx'),
        ),
    ]
