# Generated by Django 4.2.11 on 2026-05-17 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_fk_business'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulate', '0019_simulation_share_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simulationsharetoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_threshold', models.FloatField(help_text='Umbral de VaR (BOB). Alerta si VaR calculado < este valor.')),
                ('cvar_threshold', models.FloatField(blank=True, help_text='Umbral opcional de CVaR/Expected Shortfall (BOB).', null=True)),
                ('email', models.EmailField(help_text='Dirección de correo que recibirá la notificación.', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_product', models.ForeignKey(blank=True, help_text='Producto asociado (v1). Dejar en blanco para proyectos canvas v2.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_alerts', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk Alert',
                'verbose_name_plural': 'Risk Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='risk_alert_user_active')],
            },
        ),
    ]
