# Generated by Django 4.2.30 on 2026-07-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0020_add_risk_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='demand_distribution',
            field=models.CharField(blank=True, choices=[('', 'Automático (según la FDP seleccionada)'), ('gbm', 'GBM — Movimiento Browniano Geométrico (con memoria y tendencia)')], default='', help_text='Proceso de demanda a usar en el Monte Carlo. Vacío = derivar de la FDP (comportamiento por defecto i.i.d.); "gbm" = trayectoria con deriva/volatilidad calibradas desde la demanda histórica.', max_length=20),
        ),
    ]
