recommendation_data = [
    {'name': 'Recomendación 1', 
     'recommendation': 'Ajustar la cantidad máxima de unidades de tiempo.',
     'description': 'Modifica la cantidad máxima de unidades de tiempo simuladas para obtener proyecciones más precisas.'},
    {'name': 'Recomendación 2',
    'recommendation': 'Modificar el contador de unidades de tiempo.',
    'description': 'Ajusta el contador de tiempo para controlar mejor el avance de la simulación.'},
    {'name': 'Recomendación 3',
    'recommendation': 'Cambiar la tasa de llegada aleatoria de clientes.',
    'description': 'Varía la distribución de probabilidad de llegada de clientes para modelar mejor los patrones de demanda.'},   
    {'name': 'Recomendación 4',
    'recommendation': 'Variar la cantidad de productos vendidos por día.',
    'description': 'Modifica la distribución de probabilidad de ventas diarias para una estimación más precisa.'},
    {'name': 'Recomendación 5',
    'recommendation': 'Ajustar el precio de venta del producto lácteo.',
    'description': 'Actualiza el precio de venta para maximizar ingresos considerando elasticidad de la demanda.'},
    {'name': 'Recomendación 6', 
    'recommendation': 'Modificar la demanda histórica.',
    'description': 'Incorpora datos actualizados de demanda para obtener proyecciones más realistas.'},
    {'name': 'Recomendación 7',
    'recommendation': 'Cambiar la cantidad de producción esperada.', 
    'description': 'Ajusta los niveles de producción en base a las proyecciones de demanda para minimizar desperdicios.'},
    {'name': 'Recomendación 8',
    'recommendation': 'Ajustar la demanda esperada.',
    'description': 'Actualiza la demanda esperada con base en datos de mercado más recientes para planificar la producción.'},
    {'name': 'Recomendación 9',
    'recommendation': 'Modificar el costo de producción unitario.',
    'description': 'Incorpora datos actualizados de costos de producción para proyecciones financieras más precisas.'},
    {'name': 'Recomendación 10',
    'recommendation': 'Cambiar la capacidad de inventario de productos.', 
    'description': 'Ajusta el tamaño del inventario para minimizar costos de almacenamiento pero evitando quiebres de stock.'},
    {'name': 'Recomendación 11',
    'recommendation': 'Ajustar la estacionalidad de la demanda.',
    'description': 'Incorpora factores estacionales en la demanda para proyecciones de ventas más precisas.'},
    {'name': 'Recomendación 12', 
    'recommendation': 'Modificar el costo unitario del insumo para producción.',
    'description': 'Actualiza los costos de las materias primas para estimar mejor los costos de producción.'},
    {'name': 'Recomendación 13',
    'recommendation': 'Cambiar el nivel de competencia en el mercado.',
    'description': 'Ajusta la intensidad de competencia para evaluar escenarios y estrategias.'},
    {'name': 'Recomendación 14',  
    'recommendation': 'Modificar el posicionamiento de la empresa en el mercado.',
    'description': 'Cambia la participación de mercado para analizar el impacto en las finanzas.'},
    {'name': 'Recomendación 15',
    'recommendation': 'Ajustar la frecuencia de compra de los clientes.', 
    'description': 'Modifica la periodicidad de compra para proyecciones de ventas más realistas.'},
    {'name': 'Recomendación 16',
    'recommendation': 'Modificar la tasa de retención de clientes.',  
    'description': 'Ajusta la tasa de retención de clientes existentes para evaluar estrategias.'},  
    {'name': 'Recomendación 17', 
    'recommendation': 'Cambiar el nivel de satisfacción del cliente.',
    'description': 'Varía la satisfacción del cliente para analizar políticas de servicio.'},
    {'name': 'Recomendación 18',  
    'recommendation': 'Ajustar el nivel de lealtad del cliente.',
    'description': 'Modifica la lealtad de los clientes para evaluar programas de fidelización.'},
    {'name': 'Recomendación 19',
    'recommendation': 'Modificar el costo por unidad de adquisición de clientes.',  
    'description': 'Ajusta el costo de adquirir nuevos clientes con campañas de marketing.'},
    {'name': 'Recomendación 20',
    'recommendation': 'Cambiar el costo por unidad de retención de cliente.',
    'description': 'Modifica el costo de retener clientes existentes con programas especiales.'},
    {'name': 'Recomendación 21', 
    'recommendation': 'Ajustar el costo por cliente en atención.',  
    'description': 'Actualiza los gastos de servicio al cliente para proyecciones más realistas.'},
    {'name': 'Recomendación 22',
    'recommendation': 'Modificar el nivel de automatización de procesos de producción.',
    'description': 'Cambia la automatización de la producción para analizar ahorros en costos.'},  
    {'name': 'Recomendación 23', 
    'recommendation': 'Cambiar el nivel de eficiencia en el proceso de producción.',
    'description': 'Ajusta la eficiencia de producción para evaluar el impacto financiero.'},
    {'name': 'Recomendación 24',  
    'recommendation': 'Ajustar la calidad del producto final.', 
    'description': 'Modifica los estándares de calidad para evaluar escenarios.'},
    {'name': 'Recomendación 25',
    'recommendation': 'Modificar el tiempo de producción por producto.', 
    'description': 'Cambia los tiempos del proceso productivo para análisis de capacidad.'},  
    {'name': 'Recomendación 26',
    'recommendation': 'Cambiar la capacidad de producción.',  
    'description': 'Ajusta la capacidad máxima de producción para evitar restricciones.'},
    {'name': 'Recomendación 27',  
    'recommendation': 'Ajustar el nivel de flexibilidad en la producción.',
    'description': 'Modifica la flexibilidad productiva para evaluar respuesta a demanda.'},
    {'name': 'Recomendación 28',
    'recommendation': 'Modificar el nivel de eficiencia en el manejo de inventarios.',  
    'description': 'Cambia políticas de inventario para optimizar costos de almacenamiento.'},
    {'name': 'Recomendación 29',  
    'recommendation': 'Cambiar el nivel de eficiencia en la cadena de suministro.',  
    'description': 'Mejora la eficiencia de la cadena de suministro para reducir costos logísticos.'},
    {'name': 'Recomendación 30', 
    'recommendation': 'Ajustar el nivel de eficiencia en la gestión de compra de insumos.',   
    'description': 'Optimiza las compras para reducir costos de materias primas.'},
    {'name': 'Recomendación 31',
    'recommendation': 'Modificar el nivel de eficiencia en la gestión de ventas.',  
    'description': 'Mejora los procesos de venta para incrementar ingresos.'},  

    {'name': 'Recomendación 32',
    'recommendation': 'Ajustar los sueldos de los empleados.',   
    'description': 'Ajusta la estructura salarial para controlar gastos en personal.'},

    {'name': 'Recomendación 33',
    'recommendation': 'Modificar el precio promedio de los productos lácteos de la competencia.',   
    'description': 'Incorpora datos actualizados de precios de la competencia.'},  

    {'name': 'Recomendación 34',
    'recommendation': 'Cambiar el costo fijo diario.',    
    'description': 'Ajusta los costos fijos operativos para proyecciones más precisas.'},

    {'name': 'Recomendación 35', 
    'recommendation': 'Ajustar el costo unitario por transporte.',  
    'description': 'Actualiza tarifas de transporte para estimar mejor costos logísticos.'},

    {'name': 'Recomendación 36',
    'recommendation': 'Modificar el costo unitario del inventario.',    
    'description': 'Cambia el costo de mantener inventario para decisiones óptimas.'}, 

    {'name': 'Recomendación 37', 
    'recommendation': 'Cambiar los gastos de marketing mensuales.',   
    'description': 'Ajusta presupuesto de marketing para evaluar retorno de inversión.'},

    {'name': 'Recomendación 38',
    'recommendation': 'Ajustar el tiempo de reabastecimiento.',    
    'description': 'Optimiza el ciclo de reabastecimiento para mejorar flujo de efectivo.'},

    {'name': 'Recomendación 39',  
    'recommendation': 'Modificar la cantidad de insumos utilizados para fabricar un producto lácteo.',   
    'description': 'Ajusta el consumo de materias primas ante cambios tecnológicos.'},

    {'name': 'Recomendación 40',
    'recommendation': 'Cambiar la capacidad máxima de almacenamiento en inventario de productos lácteos.',    
    'description': 'Expande capacidad ante aumentos esperados de demanda.'},

    {'name': 'Recomendación 41',  
    'recommendation': 'Ajustar la cantidad de artículos producidos en cada lote de producción.',    
    'description': 'Optimiza los lotes de producción ante economías de escala.'},

    {'name': 'Recomendación 42',
    'recommendation': 'Modificar el tiempo que tarda cada empleado en producir una unidad de producto.',   
    'description': 'Ajusta productividad laboral ante cambios en automatización.'},  

    {'name': 'Recomendación 43', 
    'recommendation': 'Cambiar la calificación de la calidad del producto final.',     
    'description': 'Modifica estándares de control de calidad ante requerimientos.'},

    {'name': 'Recomendación 44',
    'recommendation': 'Ajustar el costo por unidad de transportar el producto de la fábrica a la tienda.',      
    'description': 'Actualiza tarifas de distribución para decisiones de inventario.'},

    {'name': 'Recomendación 45',  
    'recommendation': 'Modificar la demanda insatisfecha.',  
    'description': 'Incorpora la demanda insatisfecha en las proyecciones de ventas.'},

    {'name': 'Recomendación 46',
    'recommendation': 'Cambiar las ventas por cliente.',     
    'description': 'Ajusta el promedio de ventas por cliente existente ante nuevos productos.'},  

    {'name': 'Recomendación 47',  
    'recommendation': 'Ajustar los ingresos totales.',   
    'description': 'Modifica las proyecciones de ingresos ante cambios en precios o demanda.'},

    {'name': 'Recomendación 48',
    'recommendation': 'Modificar las ganancias totales.',      
    'description': 'Reestima utilidades netas ante cambios en costos o ingresos.'},

    {'name': 'Recomendación 49',  
    'recommendation': 'Cambiar la cantidad total de clientes atendidos.',     
    'description': 'Ajusta la capacidad de atención de clientes ante expansión.'},

    {'name': 'Recomendación 50',
    'recommendation': 'Ajustar el nivel de rentabilidad.',      
    'description': 'Modifica la rentabilidad esperada para evaluar inversiones.'},  

    {'name': 'Recomendación 51',  
    'recommendation': 'Modificar los gastos organizacionales.',     
    'description': 'Incorpora gastos de expansión o reestructuración.'},

    {'name': 'Recomendación 52',
    'recommendation': 'Cambiar los gastos operativos.',      
    'description': 'Ajusta gastos ante cambios en eficiencia o costos.'},

    {'name': 'Recomendación 53',  
    'recommendation': 'Ajustar los gastos generales.',   
    'description': 'Actualiza gastos generales con datos más recientes.'},

    {'name': 'Recomendación 54',
    'recommendation': 'Modificar el aleatorio de venta.',      
    'description': 'Cambia la distribución de probabilidad de ventas diarias.'},  

    {'name': 'Recomendación 55',  
    'recommendation': 'Cambiar el ingreso bruto.',     
    'description': 'Reestima ingresos ante nuevas estrategias de productos/precios.'},

    {'name': 'Recomendación 56',
    'recommendation': 'Ajustar el costo total de reorden.',      
    'description': 'Optimiza costos de reordenar inventario.'},

    {'name': 'Recomendación 57',    
    'recommendation': 'Modificar el costo total de adquisición de insumos.',
    'description': 'Minimiza costos de compra de materias primas.'},

    {'name': 'Recomendación 58',  
    'recommendation': 'Cambiar la frecuencia de llegada de clientes.',     
    'description': 'Ajusta distribución de arribos para acercarse a realidad.'},

    {'name': 'Recomendación 59',
    'recommendation': 'Ajustar el inventario de insumos.',      
    'description': 'Optimiza niveles de inventario para minimizar rupturas.'},

    {'name': 'Recomendación 60',  
    'recommendation': 'Modificar el inventario de productos finales.',     
    'description': 'Ajusta stocks de seguridad de productos ante cambios en la demanda.'},

    {'name': 'Recomendación 61',
    'recommendation': 'Cambiar el pedido de insumos.',      
    'description': ' sincroniza la adquisición de materias primas a los requerimientos de producción.'},

    {'name': 'Recomendación 62',    
    'recommendation': 'Ajustar la cantidad de clientes atendidos en el tiempo de simulación.', 
    'description': 'Expande capacidad de atención al aumentar recursos.'},

    {'name': 'Recomendación 63',
    'recommendation': 'Modificar el uso de inventario de insumos.',     
    'description': 'Optimiza manejo de materias primas ante cambios tecnológicos.'},

    {'name': 'Recomendación 64',  
    'recommendation': 'Cambiar el aleatorio de éxito de producción.',     
    'description': 'Ajusta distribución de probabilidad de defectos de calidad.'},

    {'name': 'Recomendación 65',
    'recommendation': 'Ajustar la cantidad de productos producidos.',      
    'description': 'Reestima producción esperada ante cambios en la demanda.'}, 

    {'name': 'Recomendación 66',  
    'recommendation': 'Modificar los gastos totales.',
    'description': 'Incorpora datos actualizados de todos los gastos operativos.'}
    ]

