finance_data = [
    {'name': 'Recomendación-1', 
     'recommendation': 'Diversificación de productos', 
     'description': 'Considera expandir la línea de productos lácteos para llegar a nuevos mercados y diversificar las fuentes de ingresos.'},
    {'name': 'Recomendación-2', 
     'recommendation': 'Optimización de costos de producción', 
     'description': 'Realiza un análisis detallado de los costos de producción y busca oportunidades de reducción de gastos sin comprometer la calidad del producto. Esto puede incluir la mejora de procesos, la negociación de mejores precios con proveedores y la optimización de la cadena de suministro.'},
    {'name': 'Recomendación-3', 
     'recommendation': 'Gestión de inventario', 
     'description': 'Implementa un sistema eficiente de gestión de inventario para evitar el exceso de stock y minimizar las pérdidas por productos vencidos. Esto ayudará a mantener un flujo de efectivo saludable y reducirá los costos de almacenamiento.'},
    {'name': 'Recomendación-4', 
     'recommendation': 'Estrategias de precios', 
     'description': 'Analiza el mercado y ajusta estratégicamente los precios de tus productos lácteos para ser competitivos y maximizar los ingresos. Considera promociones, descuentos por volumen y ofertas especiales para atraer a más clientes.'},
    {'name': 'Recomendación-5', 
     'recommendation': 'Planificación financiera', 
     'description': 'Elabora un plan financiero a largo plazo que incluya proyecciones de ingresos y gastos, análisis de riesgos y estrategias de crecimiento. Esto te permitirá tomar decisiones financieras más informadas y gestionar los recursos de manera eficiente.'},
    {'name': 'Recomendación-6', 
     'recommendation': 'Búsqueda de financiamiento', 
     'description': 'Explora opciones de financiamiento externo, como préstamos bancarios o inversionistas, para respaldar el crecimiento de la empresa o cubrir necesidades de capital de trabajo. Asegúrate de evaluar cuidadosamente los términos y condiciones antes de comprometerte.'},
    {'name': 'Recomendación-7', 
     'recommendation': 'Inversión en tecnología', 
     'description': 'Considera invertir en tecnología moderna y sistemas de información que puedan mejorar la eficiencia operativa, la gestión de inventario, la toma de decisiones y la relación con los clientes. Esto puede incluir la implementación de un sistema de gestión empresarial (ERP) o herramientas de análisis de datos.'},
    {'name': 'Recomendación-8', 
     'recommendation': 'Análisis de riesgos', 
     'description': 'Realiza una evaluación de riesgos para identificar posibles amenazas y tomar medidas preventivas. Establece un fondo de contingencia para hacer frente a situaciones imprevistas y minimizar el impacto financiero en caso de eventos adversos.'},
    {'name': 'Recomendación-9', 
     'recommendation': 'Evaluación de alianzas estratégicas', 
     'description': 'Explora oportunidades de colaboración con otras empresas del sector lácteo para aprovechar sinergias y beneficiarse de economías de escala.'},
    {'name': 'Recomendación-10', 
     'recommendation': 'Mantenimiento de relaciones con clientes', 
     'description': 'Fomenta relaciones sólidas con tus clientes y busca mantener su fidelidad. Ofrece un servicio al cliente excepcional, desarrolla programas de lealtad y recopila feedback para mejorar constantemente la calidad de tus productos y servicios. Esto contribuirá a generar ingresos recurrentes y a largo plazo.'},
]
