import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "findempro.settings")  # Reemplaza 'tu_proyecto' con el nombre de tu proyecto.
django.setup()

from variable.models import Variable  # Reemplaza 'your_app' con el nombre de tu aplicación.

variables_data = [
{'name': 'NÚMERO MÁXIMO UNIDAD DE TIEMPO',
'initials': 'NMD',
'type': 'EXÓGENA',
'unit': 'UNIDAD DE TIEMPO',
'description': 'CANTIDAD DE UNIDAD DE TIEMPO'},

{'name': 'CONTADOR UNIDAD DE TIEMPO',
'initials': 'CD',
'type': 'ESTADO',
'unit': 'UNIDAD DE TIEMPO',
'description': 'CONTADOR DE UNIDAD DE TIEMPO QUE PASAN'},

{'name': 'ALEATORIO LLEGADA DE CLIENTES',
'initials': 'ALC',
'type': 'ESTADO',
'unit': '[0-1]',
'description': 'ALEATORIO PARA GENERAR EL NÚMERO DE CLIENTES'},

{'name': 'CANTIDAD DE PRODUCTOS QUE VENDE POR DIA',
'initials': 'CPVD',
'type': 'EXÓGENA',
'unit': 'LITROS/UNIDAD DE TIEMPO',
'description': 'CANTIDAD DE LITROS DEL PRODUCTO QUE LA EMPRESA VENDE POR UNIDAD DE TIEMPO'},

{'name': 'PRECIO DE VENTA DEL PRODUCTO',
'initials': 'PVP',
'type': 'EXÓGENA',
'unit': 'BS',
'description': 'PRECIO DE VENTA DEL PRODUCTO LÁCTEO'},

{'name': 'DEMANDA HISTÓRICA',
'initials': 'DH',
'type': 'EXÓGENA',
'unit': 'LITROS',
'description': 'DATOS HISTÓRICOS DE DEMANDA DE LOS ÚLTIMOS UNIDADES DE TIEMPO'},

{'name': 'CANTIDAD DE PRODUCCIÓN',
'initials': 'CP',
'type': 'EXÓGENA',
'unit': 'LITROS',
'description': 'CANTIDAD DE PRODUCTOS ESPERADOS A VENDER EN UN PERIODO DE TIEMPO'},

{'name': 'DEMANDA ESPERADA',
'initials': 'DE',
'type': 'EXÓGENA',
'unit': 'LITROS/BS',
'description': 'DEMANDA ESPERADA EN EL PERIODO DE TIEMPO ESTABLECIDO'},

{'name': 'COSTO DE PRODUCCIÓN UNITARIO',
'initials': 'CPU',
'type': 'EXÓGENA',
'unit': 'BS',
'description': 'COSTO UNITARIO POR LA PRODUCCIÓN'},

{'name': 'CAPACIDAD INVENTARIO PRODUCTOS',
'initials': 'CIP',
'type': 'EXÓGENA',
'unit': 'LITROS',
'description': 'CAPACIDAD MÁXIMA QUE LA EMPRESA PUEDE ALMACENAR EN INVENTARIO'},

{'name': 'ESTACIONALIDAD DE LA DEMANDA',
'initials': 'ED',
'type': 'EXÓGENA',
'unit': '[0-1]',
'description': 'VARIACIONES PREDECIBLES DE LA DEMANDA DE UN PRODUCTO O SERVICIO EN MOMENTOS ESPECÍFICOS DEL AÑO.'},

{'name': 'COSTO UNITARIO INSUMO PRODUCCIÓN',
'initials': 'CUIP',
'type': 'EXÓGENA',
'unit': 'LITROS/BS',
'description': 'COSTO QUE LE CUESTA A LA EMPRESA POR INSUMO'},

{'name': 'NIVEL DE COMPETENCIA EN EL MERCADO',
'initials': 'NCM',
'type': 'EXÓGENA',
'unit': '[0-1]',
'description': 'EL NIVEL QUE LA EMPRESA TIENE DE COMPETENCIA EN EL MERCADO'},

{'name': 'POSICIONAMIENTO DE LA EMPRESA',
'initials': 'PE',
'type': 'EXÓGENA',
'unit': '[0-1]',
'description': 'Cuál ES EL POSICIONAMIENTO DE LA EMPRESA EN EL MERCADO'},

{'name': 'FRECUENCIA DE COMPRA',
'initials': 'FC',
'type': 'EXÓGENA',
'unit': 'UNIDAD DE TIEMPO',
'description': 'CON QUÉ FRECUENCIA SUS CLIENTES COMPRAN PRODUCTOS DE SU EMPRESA'},

{'name': 'TASA DE RETENCIÓN CLIENTES',
'initials': 'TRC',
'type': 'EXÓGENA',
'unit': '[0-1]',
'description': 'PORCENTAJE DE RETENCIÓN DE LOS CLIENTES QUE COMPRAN'},

{'name': 'SATISFACCIÓN DEL CLIENTE',
'initials': 'SC',
'type': 'EXÓGENA',
'unit': '[0-1]',
'description': 'NIVEL DE SATISFACCIÓN DEL CLIENTE CON LOS PRODUCTOS'},

{'name': 'NIVEL LEALTAD DEL CLIENTE',
'initials': 'NLC',
'type': 'EXÓGENA',
'unit': '[0-1]',
'description': 'NIVEL DE LEALTAD QUE TIENE EL CLIENTE CON LOS PRODUCTOS DE LA EMPRE'},

{'name': 'COSTO UNITARIO DE ADQUISICIÓN DE CLIENTES',
'initials': 'CUAC',
'type': 'EXÓGENA',
'unit': 'CLIENTE/BS',
'description': 'EL GASTO PROMEDIO NECESARIO PARA CONSEGUIR QUE UN CLIENTE REALICE UNA COMPRA'},

{'name': 'COSTO UNITARIO DE RETENCIÓN DE CLIENTE',
'initials': 'CURC',
'type': 'EXÓGENA',
'unit': 'CLIENTE/BS',
'description': 'EL GASTO PROMEDIO QUE UNA EMPRESA INCURRE PARA MANTENER A UN CLIENTE EXISTENTE DURANTE UN PERÍODO DETERMINADO'},

{'name': 'CLIENTES POR DÍA',
'initials': 'CPD',
'type': 'EXÓGENA',
'unit': 'CLIENTE/BS',
'description': 'COSTO POR CLIENTE EN ATENCIÓN'},

{'name': 'NIVEL AUTOMATIZACIÓN DE PROCESO PRODUCCIÓN',
'initials': 'NAPP',
'type': 'EXÓGENA',
'unit': '[0-1]',
'description': 'NIVEL DE AUTOMATIZACIÓN DE LOS PROCESOS DE PRODUCCIÓN DE LA EMPRESA'},

{'name': 'NIVEL EFICIENCIA EN EL PROCESO DE PRODUCCIÓN',
'initials': 'NEPP',
'type': 'EXÓGENA',
'unit': '[0-1]',
'description': 'NIVEL DE EFICIENCIA EN EL PROCESO DE PRODUCCIÓN DE LOS PRODUCTOS'},

{'name': 'CALIDAD DEL PRODUCTO',
'initials': 'CP',
'type': 'EXÓGENA',
'unit': '[0-1]',
'description': 'NIVEL DE CALIDAD DEL PRODUCTO FINAL'},

{'name': 'TIEMPO PRODUCCIÓN POR PRODUCTO',
'initials': 'TPP',
'type': 'EXÓGENA',
'unit': 'MINUTOS',
'description': 'EL TIEMPO QUE SE TOMA LA EMPRESA POR LA PRODUCCIÓN DE UN PRODUCTO'},

{'name': 'CAPACIDAD DE PRODUCCIÓN',
'initials': 'CP',
'type': 'EXÓGENA',
'unit': 'LITROS/UNIDAD DE TIEMPO',
'description': 'NIVEL DE CAPACIDAD'},

{'name': 'NIVEL FLEXIBILIDAD EN LA PRODUCCIÓN',
'initials': 'NFP',
'type': 'EXÓGENA',
'unit': '[0.1,0.2,0.3,0.4,0.5]',
'description': 'NIVEL DE FLEXIBILIDAD DE LOS PROCESOS DE PRODUCCIÓN DE LA EMPRESA'},

{'name': 'NIVEL DE EFICIENCIA DE INVENTARIO',
'initials': 'NEI',
'type': 'EXÓGENA',
'unit': '[0.1,0.2,0.3,0.4,0.5]',
'description': 'NIVEL DE EFICIENCIA EN EL MANEJO DE INVENTARIOS'},

{'name': 'NIVEL EFICIENCIA CADENA SUMINISTRO',
'initials': 'NECS',
'type': 'EXÓGENA',
'unit': '[0.1,0.2,0.3,0.4,0.5]',
'description': 'NIVEL DE EFICIENCIA EN LA CADENA DE SUMINISTRO'},

{'name': 'NIVEL EFICIENCIA GESTIÓN DE COMPRA INSUMOS',
'initials': 'NEGOCIO',
'type': 'EXÓGENA',
'unit': '[0.1,0.2,0.3,0.4,0.5]',
'description': 'NIVEL DE EFICIENCIA EN LA GESTIÓN DE COMPRA DE INSUMOS'},

{'name': 'NIVEL DE EFICIENCIA EN LA GESTIÓN DE VENTAS',
'initials': 'NEGV',
'type': 'EXÓGENA',
'unit': '[0.1,0.2,0.3,0.4,0.5]',
'description': 'NIVEL DE EFICIENCIA EN LA GESTIÓN DE VENTAS'},

{'name': 'SUELDOS EMPLEADOS',
'initials': 'SE',
'type': 'EXÓGENA',
'unit': 'BS',
'description': 'NIVEL DE DEUDAS DE LA EMPRESA'},

{'name': 'PRECIO DE VENTA PROMEDIO DE LOS PRODUCTOS DE LA COMPETENCIA',
'initials': 'PVPCC',
'type': 'EXÓGENA',
'unit': 'BS',
'description': 'PRECIO DE VENTA DEL MISMO PRODUCTO PERO DE LA COMPETENCIA'},

{'name': 'COSTO FIJO DIARIO',
'initials': 'CFD',
'type': 'EXÓGENA',
'unit': 'BS',
'description': 'COSTO DE MATERIALES TERCEROS PARA LA PRODUCCIÓN DE BIENES'},

{'name': 'COSTO UNITARIO POR TRANSPORTE',
'initials': 'CUP',
'type': 'EXÓGENA',
'unit': 'LITROS/BS',
'description': 'COSTO UNITARIO POR TRANSPORTE DE UN BIEN FINAL DE LA FÁBRICA A LA TIENDA'},

{'name': 'COSTO UNITARIO INVENTARIO',
'initials': 'CUI',
'type': 'EXÓGENA',
'unit': 'BS',
'description': 'EL COSTO POR UNIDAD DE MANTENER INVENTARIO, INCLUYENDO ALMACENAMIENTO, SEGUROS, DEPRECIACIÓN Y OPORTUNIDAD DE CAPITAL INMOVILIZADO.'},

{'name': 'GASTOS DE MARKETING MENSUAL',
'initials': 'GMM',
'type': 'EXÓGENA',
'unit': 'LITROS/BS',
'description': 'CANTIDAD DE DINERO INVERTIDA EN ACTIVIDADES DE MARKETING DURANTE UN MES DETERMINADO PARA PROMOCIONAR PRODUCTOS O SERVICIOS.'},

{'name': 'TIEMPO REABASTECIMIENTO',
'initials': 'TR',
'type': 'EXÓGENA',
'unit': 'UNIDAD DE TIEMPO',
'description': 'ES EL PERIODO NECESARIO PARA REPONER EL INVENTARIO DE UN PRODUCTO UNA VEZ AGOTADO.'},

{'name': 'CANTIDAD DE INSUMOS PARA UN PRODUCTO',
'initials': 'CIP',
'type': 'EXÓGENA',
'unit': 'LITROS',
'description': 'CANTIDAD QUE LA EMPRESA UTILIZA PAR LA PRODUCCIÓN DE UN INSUMO'},

{'name': 'TOTAL PRODUCTOS VENDIDOS',
'initials': 'TPV',
'type': 'ENDÓGENA',
'unit': 'LITROS',
'description': 'CANTIDAD TOTAL DE PRODUCTOS VENDIDOS DE LA EMPRESA DURANTE UN PERIODO DETERMINADO'},

{'name': 'TOTAL PRODUCTOS PRODUCIDOS',
'initials': 'TPP',
'type': 'ENDÓGENA',
'unit': 'LITROS',
'description': 'CANTIDAD TOTAL DE PRODUCTOS PRODUCIDOS DE LA EMPRESA DURANTE UN PERIODO DETERMINADO'},

{'name': 'DEMANDA INSATISFECHA',
'initials': 'DI',
'type': 'ENDÓGENA',
'unit': 'LITROS',
'description': 'CANTIDAD DE PRODUCTOS QUE NO ESTUVIERON DISPONIBLES PARA LA VENTA'},

{'name': 'VENTAS POR CLIENTE',
'initials': 'VPC',
'type': 'ENDÓGENA',
'unit': 'LITROS',
'description': 'CANTIDAD DE PRODUCTOS VENDIDOS EN EL SECTOR LÁCTEO, VARIABLE UTILIZADA PARA LA TOMA DE DECISIONES FINANCIERAS EN LA PLATAFORMA WEB.'},

{'name': 'INGRESOS TOTALES',
'initials': 'IT',
'type': 'ENDÓGENA',
'unit': 'BS',
'description': 'CANTIDAD TOTAL DE INGRESOS GENERADOS POR LAS PYMES DEL SECTOR LÁCTEO, UTILIZADA EN LA TOMA DE DECISIONES FINANCIERAS EN LA PLATAFORMA WEB.'},

{'name': 'GANANCIAS TOTALES',
'initials': 'GT',
'type': 'ENDÓGENA',
'unit': 'BS',
'description': 'MONTO TOTAL DE GANANCIAS GENERADAS POR LAS PYMES DEL SECTOR LÁCTEO, UTILIZADA EN LA TOMA DE DECISIONES FINANCIERAS EN EL SISTEMA WEB.'},

{'name': 'TOTAL CLIENTES ATENDIDOS',
'initials': 'TCA',
'type': 'ENDÓGENA',
'unit': 'BS',
'description': 'GANANCIAS GENERADAS POR LAS PYMES LÁCTEAS, RESULTADO DE LA DIFERENCIA ENTRE INGRESOS Y COSTOS, UTILIZADAS PARA LA TOMA DE DECISIONES FINANCIERAS EN EL SISTEMA WEB.'},

{'name': 'NIVEL DE RENTABILIDAD',
'initials': 'NR',
'type': 'ENDÓGENA',
'unit': '[0.1,0.2,0.3,0.4,0.5]',
'description': 'NIVEL DE RENTABILIDAD DE LA EMPRESA'},

{'name': 'GASTOS ORGANIZACIONALES',
'initials': 'GO',
'type': 'ENDÓGENA',
'unit': 'BS',
'description': 'GASTOS TOTALES EN OPERACIONES Y ADMINISTRACIÓN DE LAS PYMES DEL SECTOR LÁCTEO, UTILIZADOS EN EL SISTEMA WEB PARA LA TOMA DE DECISIONES FINANCIERAS.'},

{'name': 'GASTOS OPERATIVOS',
'initials': 'GO',
'type': 'ENDÓGENA',
'unit': 'BS',
'description': 'COSTOS NECESARIOS PARA EL FUNCIONAMIENTO DIARIO DE LAS PYMES DEL SECTOR LÁCTEO, VARIABLE RELEVANTE EN LA TOMA DE DECISIONES FINANCIERAS.'},

{'name': 'GASTOS GENERALES',
'initials': 'GG',
'type': 'ENDÓGENA',
'unit': 'BS',
'description': 'COSTOS OPERATIVOS Y ADMINISTRATIVOS EN LAS PYMES DEL SECTOR LÁ'
},

{'name': 'ALEATORIO VENTA',
'initials': 'AV',
'type': 'ESTADO',
'unit': '[0-1]',
'description': 'CANTIDAD DE INSUMOS REQUERIDOS PARA LA PRODUCCIÓN DE BIENES O SERVICIOS, SUJETA A VARIACIONES ALEATORIAS EN EL SISTEMA.'},

{'name': 'INGRESO BRUTO',
'initials': 'IB',
'type': 'ESTADO',
'unit': 'BS',
'description': 'TOTAL DE INGRESOS OBTENIDOS ANTES DE DEDUCIR LOS GASTOS Y LOS IMPUESTOS, MEDIDA FINANCIERA UTILIZADA PARA EVALUAR LA RENTABILIDAD.'},

{'name': 'COSTO TOTAL REORDEN',
'initials': 'CTR',
'type': 'ESTADO',
'unit': 'LITROS/BS',
'description': 'EL COSTO TOTAL DE REALIZAR UN NUEVO PEDIDO DE INVENTARIO, INCLUYENDO EL COSTO DE ADQUISICIÓN, TRANSPORTE Y ALMACENAMIENTO.'},

{'name': 'COSTO TOTAL ADQUISICIÓN INSUMOS',
'initials': 'CTAI',
'type': 'ESTADO',
'unit': 'BS',
'description': 'GASTO TOTAL EN LA ADQUISICIÓN DE INSUMOS UTILIZADOS EN LA PRODUCCIÓN'},

{'name': 'LLEGADA DE CLIENTES',
'initials': 'LC',
'type': 'ESTADO',
'unit': 'BS',
'description': 'FRECUENCIA CON LA QUE LOS CLIENTES LLEGAN A UN ESTABLECIMIENTO O NEGOCIO'},

{'name': 'INVENTARIO INSUMOS',
'initials': 'II',
'type': 'ESTADO',
'unit': 'LITROS',
'description': 'CANTIDAD DE INSUMOS EXISTENTES EN INVENTARIO'},

{'name': 'INVENTARIO PRODUCTOS FINALES',
'initials': 'IPF',
'type': 'ESTADO',
'unit': 'LITROS',
'description': 'CANTIDAD DE INSUMOS QUE SE USA AL REALIZAR UNA VENTA'},

{'name': 'PEDIDO INSUMOS',
'initials': 'PI',
'type': 'ESTADO',
'unit': 'LITROS',
'description': 'CANTIDAD DE VÍVERES QUE SE PIDEN AL REORDENAR PARA EL REABASTECIMIENTO DE INVENTARIO'},

{'name': 'TOTAL CLIENTES ATENDIDOS EN EL UNIDAD DE TIEMPO',
'initials': 'TCAE',
'type': 'ESTADO',
'unit': 'CLIENTES',
'description': 'NÚMERO TOTAL DE CLIENTES QUE FUERON ATENDIDOS'},

{'name': 'USO DE INVENTARIO INSUMOS',
'initials': 'UII',
'type': 'ESTADO',
'unit': 'LITROS',
'description': 'AUXILIAR CANTIDAD DE INSUMOS QUE SE USA AL REALIZAR UNA VENTA'},

{'name': 'ALEATORIO EXITO PRODUCCIÓN',
'initials': 'AEP',
'type': 'ESTADO',
'unit': '[0-1]',
'description': 'ALEATORIO PARA GENERAR EL NÚMERO DE CLIENTES'},

{'name': 'PRODUCTOS PRODUCIDOS',
'initials': 'PP',
'type': 'ESTADO',
'unit': 'LITROS',
'description': 'CANTIDAD TOTAL DE PRODUCTOS LÁCTEOS FABRICADOS'},

{'name': 'GASTOS TOTALES',
'initials': 'GT',
'type': 'ENDÓGENA',
'unit': 'BS',
'description': 'GASTOS TOTALES EN EL TIEMPO DE SIMULACIÓN'}

]

for data in variables_data:
    Variable.objects.create(**data)

# python generate_variables.py