variables_data = [
{'name': 'PRECIO DE VENTA DEL PRODUCTO',
'initials': 'PVP',
'type': 1,
'unit': 'BS',
'description': 'PRECIO DE VENTA DEL PRODUCTO LÁCTEO'},

{'name': 'DEMANDA HISTÓRICA',
'initials': 'DH',
'type': 1,
'unit': 'L',
'description': 'DATOS HISTÓRICOS DE DEMANDA DE LOS ÚLTIMOS UNIDADES DE TIEMPO'},

{'name': 'DEMANDA ESPERADA',
'initials': 'DE',
'type': 1,
'unit': 'L/BS',
'description': 'DEMANDA ESPERADA EN EL PERIODO DE TIEMPO ESTABLECIDO'},

{'name': 'CAPACIDAD INVENTARIO PRODUCTOS',
'initials': 'CIP',
'type': 1,
'unit': 'L',
'description': 'CAPACIDAD MÁXIMA QUE LA EMPRESA PUEDE ALMACENAR EN INVENTARIO'},

{'name': 'ESTACIONALIDAD DE LA DEMANDA',
'initials': 'ED',
'type': 1,
'unit': '[0-1]',
'description': 'VARIACIONES PREDECIBLES DE LA DEMANDA DE UN PRODUCTO O SERVICIO EN MOMENTOS ESPECÍFICOS DEL AÑO.'},

{'name': 'COSTO UNITARIO INSUMO PRODUCCIÓN',
'initials': 'CUIP',
'type': 1,
'unit': 'L/BS',
'description': 'COSTO QUE LE CUESTA A LA EMPRESA POR INSUMO'},

{'name': 'NIVEL DE COMPETENCIA EN EL MERCADO',
'initials': 'NCM',
'type': 3,
'unit': '[0-1]',
'description': 'EL NIVEL QUE LA EMPRESA TIENE DE COMPETENCIA EN EL MERCADO'},

{'name': 'FRECUENCIA DE COMPRA',
'initials': 'FC',
'type': 3,
'unit': 'DIAS',
'description': 'CON QUÉ FRECUENCIA SUS CLIENTES COMPRAN PRODUCTOS DE SU EMPRESA'},

{"name": "Tiempo Promedio entre Compras",
  "initials": "TPC",
  "type": 1,
  "unit": "DÍAS",
  "description": "Tiempo promedio que transcurre entre las compras de los clientes de la empresa"
},

{'name': 'COSTO UNITARIO DE ADQUISICIÓN DE CLIENTES',
'initials': 'CUAC',
'type': 3,
'unit': 'CLIENTE/BS',
'description': 'EL GASTO PROMEDIO NECESARIO PARA CONSEGUIR QUE UN CLIENTE REALICE UNA COMPRA'},

{'name': 'CLIENTES POR DÍA',
'initials': 'CPD',
'type': 1,
'unit': 'CLIENTE/BS',
'description': 'COSTO POR CLIENTE EN ATENCIÓN'},

{'name': 'NUMERO DE EMPLEADOS',
'initials': 'NEPP',
'type': 1,
'unit': 'EMPLEADOS',
'description': 'Numero de empleados'},

{'name': 'Cantidad producida de productos lácteos',
'initials': 'QPL',
'type': 2,
'unit': 'L',
'description': 'Cantidad producida de productos lácteos'},

{'name': 'CAPACIDAD DE PRODUCCIÓN',
'initials': 'CPROD',
'type': 2,
'unit': 'L/DIAS',
'description': 'Capacidad de produccion'},

{'name': 'Cantidad Promedio Producción por Lote',
'initials': 'CPPL',
'type': 1,
'unit': 'UNIDADES',
'description': 'Cantidad Promedio Producción por Lote'},

{'name': 'Tiempo de produccion por empleado',
'initials': 'TPE',
'type': 1,
'unit': 'DIAS',
'description': 'Tiempo de produccion por empleado'},


{'name': 'SUELDOS EMPLEADOS',
'initials': 'SE',
'type': 1,
'unit': 'BS',
'description': 'SUELDOS EMPLEADOS'},

{'name': 'PRECIO DE VENTA DE LA COMPETENCIA',
'initials': 'PC',
'type': 1,
'unit': 'BS',
'description': 'PRECIO DE VENTA DEL MISMO PRODUCTO PERO DE LA COMPETENCIA'},

{'name': 'COSTO FIJO DIARIO',
'initials': 'CFD',
'type': 1,
'unit': 'BS',
'description': 'COSTO FIJO DIARIO DE LA EMPRESA'},

{'name': 'COSTO UNITARIO POR TRANSPORTE',
'initials': 'CUTRANS',
'type': 1,
'unit': 'L/BS',
'description': 'COSTO UNITARIO POR TRANSPORTE DE UN BIEN FINAL DE LA FÁBRICA A LA TIENDA'},

{'name': 'COSTO UNITARIO INVENTARIO',
'initials': 'CUI',
'type': 3,
'unit': 'BS',
'description': 'EL COSTO POR UNIDAD DE MANTENER INVENTARIO, INCLUYENDO ALMACENAMIENTO, SEGUROS, DEPRECIACIÓN Y OPORTUNIDAD DE CAPITAL INMOVILIZADO.'},

{'name': 'GASTO TOTAL MARKETING',
'initials': 'GMM',
'type': 1,
'unit': 'BS',
'description': 'CANTIDAD DE DINERO INVERTIDA EN ACTIVIDADES DE MARKETING DURANTE UN MES DETERMINADO PARA PROMOCIONAR PRODUCTOS O SERVICIOS.'},

{'name': 'TIEMPO REABASTECIMIENTO',
'initials': 'TR',
'type': 1,
'unit': 'DIAS',
'description': 'ES EL PERIODO NECESARIO PARA REPONER EL INVENTARIO DE UN PRODUCTO UNA VEZ AGOTADO.'},

{'name': 'CANTIDAD DE INSUMOS PARA UN PRODUCTO',
'initials': 'CIP',
'type': 1,
'unit': 'L',
'description': 'CANTIDAD QUE LA EMPRESA UTILIZA PAR LA PRODUCCIÓN DE UN INSUMO'},

{'name': 'CAPACIDAD MÁXIMA INVENTARIO PRODUCTO FINAL',
'initials': 'CMIPF',
'type': 1,
'unit': 'L',
'description': 'CAPACIDAD MAXIMA DE INSUMOS DEL PRODUCTO FINAL'},

{'name': 'NUMERO MAXIMO DE DIAS',
'initials': 'NMD',
'type': 1,
'unit': 'DIAS',
'description': 'CAPACIDAD MAXIMA DE INSUMOS DEL PRODUCTO FINAL'},

{'name': 'Tiempo Formulación Pedido',
'initials': 'DF',
'type': 1,
'unit': 'DIAS',
'description': 'Tiempo Formulación Pedido'},

{'name': 'Pedido Reabastecimiento Leche bRUTA',
'initials': 'PRL',
'type': 1,
'unit': 'DIAS',
'description': 'CAPACIDAD MAXIMA DE INSUMOS DEL PRODUCTO FINAL'},

{'name': 'Tiempo Formulación Pedido',
'initials': 'NPD',
'type': 1,
'unit': 'DIAS',
'description': 'CAPACIDAD MAXIMA DE INSUMOS DEL PRODUCTO FINAL'},

{'name': 'Nivel Ideal del Inventario Leche',
'initials': 'NIL',
'type': 3,
'unit': 'DIAS',
'description': 'CAPACIDAD MAXIMA DE INSUMOS DEL PRODUCTO FINAL'},

{'name': 'Stock de Inventario mínimo de Seguridad',
'initials': 'SI',
'type': 1,
'unit': 'L',
'description': 'Stock de Inventario mínimo de Seguridad'},

{'name': 'Días Promedio de Reposición de Leche',
'initials': 'DPL',
'type': 1,
'unit': 'DIAS',
'description': 'Días Promedio de Reposición de Leche'},

{'name': 'Consumo diario promedio',
'initials': 'CTL',
'type': 1,
'unit': 'L',
'description': 'Consumo diario promedio'},

{'name': 'ALEATORIO LLEGADA DE CLIENTES',
'initials': 'ALC',
'type': 2,
'unit': '[0-1]',
'description': 'ALEATORIO PARA GENERAR EL NÚMERO DE CLIENTES'},

{'name': 'ALEATORIO VENTA',
'initials': 'AV',
'type': 2,
'unit': '[0-1]',
'description': 'CANTIDAD DE INSUMOS REQUERIDOS PARA LA PRODUCCIÓN DE BIENES O SERVICIOS, SUJETA A VARIACIONES ALEATORIAS EN EL SISTEMA.'},

{'name': 'INGRESO BRUTO',
'initials': 'IB',
'type': 2,
'unit': 'BS',
'description': 'TOTAL DE INGRESOS OBTENIDOS ANTES DE DEDUCIR LOS GASTOS Y LOS IMPUESTOS, MEDIDA FINANCIERA UTILIZADA PARA EVALUAR LA RENTABILIDAD.'},


{'name': 'LLEGADA DE CLIENTES',
'initials': 'LC',
'type': 2,
'unit': 'BS',
'description': 'FRECUENCIA CON LA QUE LOS CLIENTES LLEGAN A UN ESTABLECIMIENTO O NEGOCIO'},

{'name': 'INVENTARIO INSUMOS',
'initials': 'II',
'type': 2,
'unit': 'L',
'description': 'CANTIDAD DE INSUMOS EXISTENTES EN INVENTARIO'},

{'name': 'INVENTARIO PRODUCTOS FINALES',
'initials': 'IPF',
'type': 2,
'unit': 'L',
'description': 'CANTIDAD DE INSUMOS QUE SE USA AL REALIZAR UNA VENTA'},

{'name': 'PEDIDO INSUMOS',
'initials': 'PI',
'type': 2,
'unit': 'L',
'description': 'CANTIDAD DE VÍVERES QUE SE PIDEN AL REORDENAR PARA EL REABASTECIMIENTO DE INVENTARIO'},

{'name': 'TOTAL CLIENTES ATENDIDOS EN EL DIAS',
'initials': 'TCAE',
'type': 2,
'unit': 'CLIENTES',
'description': 'NÚMERO TOTAL DE CLIENTES QUE FUERON ATENDIDOS'},

{'name': 'USO DE INVENTARIO INSUMOS',
'initials': 'UII',
'type': 2,
'unit': 'L',
'description': 'AUXILIAR CANTIDAD DE INSUMOS QUE SE USA AL REALIZAR UNA VENTA'},

{'name': 'ALEATORIO EXITO PRODUCCIÓN',
'initials': 'AEP',
'type': 2,
'unit': '[0-1]',
'description': 'ALEATORIO PARA GENERAR EL NÚMERO DE CLIENTES'},

{'name': 'PRODUCTOS PRODUCIDOS',
'initials': 'PPL',
'type': 2,
'unit': 'L',
'description': 'CANTIDAD TOTAL DE PRODUCTOS LÁCTEOS FABRICADOS'},

{'name': 'COSTO TOTAL REORDEN',
'initials': 'CTR',
'type': 3,
'unit': 'L/BS',
'description': 'EL COSTO TOTAL DE REALIZAR UN NUEVO PEDIDO DE INVENTARIO, INCLUYENDO EL COSTO DE ADQUISICIÓN, TRANSPORTE Y ALMACENAMIENTO.'},

{'name': 'COSTO TOTAL ADQUISICIÓN INSUMOS',
'initials': 'CTAI',
'type': 3,
'unit': 'BS',
'description': 'GASTO TOTAL EN LA ADQUISICIÓN DE INSUMOS UTILIZADOS EN LA PRODUCCIÓN'},

{'name': 'TOTAL PRODUCTOS VENDIDOS',
'initials': 'TPV',
'type': 3,
'unit': 'L',
'description': 'CANTIDAD TOTAL DE PRODUCTOS VENDIDOS DE LA EMPRESA DURANTE UN PERIODO DETERMINADO'},

{'name': 'TOTAL PRODUCTOS PRODUCIDOS',
'initials': 'TPPRO',
'type': 3,
'unit': 'L',
'description': 'CANTIDAD TOTAL DE PRODUCTOS PRODUCIDOS DE LA EMPRESA DURANTE UN PERIODO DETERMINADO'},

{'name': 'DEMANDA INSATISFECHA',
'initials': 'DI',
'type': 3,
'unit': 'L',
'description': 'CANTIDAD DE PRODUCTOS QUE NO ESTUVIERON DISPONIBLES PARA LA VENTA'},

{'name': 'VENTAS POR CLIENTE',
'initials': 'VPC',
'type': 3,
'unit': 'L',
'description': 'CANTIDAD DE PRODUCTOS VENDIDOS EN EL SECTOR LÁCTEO, VARIABLE UTILIZADA PARA LA TOMA DE DECISIONES FINANCIERAS EN LA PLATAFORMA WEB.'},

{'name': 'INGRESOS TOTALES',
'initials': 'IT',
'type': 3,
'unit': 'BS',
'description': 'CANTIDAD TOTAL DE INGRESOS GENERADOS POR LAS PYMES DEL SECTOR LÁCTEO, UTILIZADA EN LA TOMA DE DECISIONES FINANCIERAS EN LA PLATAFORMA WEB.'},

{'name': 'GANANCIAS TOTALES',
'initials': 'GT',
'type': 3,
'unit': 'BS',
'description': 'MONTO TOTAL DE GANANCIAS GENERADAS POR LAS PYMES DEL SECTOR LÁCTEO, UTILIZADA EN LA TOMA DE DECISIONES FINANCIERAS EN EL SISTEMA WEB.'},

{'name': 'TOTAL CLIENTES ATENDIDOS',
'initials': 'TCA',
'type': 3,
'unit': 'CLIENTES',
'description': 'GANANCIAS GENERADAS POR LAS PYMES LÁCTEAS, RESULTADO DE LA DIFERENCIA ENTRE INGRESOS Y COSTOS, UTILIZADAS PARA LA TOMA DE DECISIONES FINANCIERAS EN EL SISTEMA WEB.'},

{'name': 'NIVEL DE RENTABILIDAD',
'initials': 'NR',
'type': 3,
'unit': '[0.1,0.3,0.5]',
'description': 'NIVEL DE RENTABILIDAD DE LA EMPRESA'},

{'name': 'GASTOS OPERATIVOS',
'initials': 'GO',
'type': 3,
'unit': 'BS',
'description': 'COSTOS NECESARIOS PARA EL FUNCIONAMIENTO DIARIO DE LAS PYMES DEL SECTOR LÁCTEO, VARIABLE RELEVANTE EN LA TOMA DE DECISIONES FINANCIERAS.'},

{'name': 'GASTOS GENERALES',
'initials': 'GG',
'type': 3,
'unit': 'BS',
'description': 'COSTOS OPERATIVOS Y ADMINISTRATIVOS EN LAS PYMES DEL SECTOR LÁ'
},

{'name': 'GASTOS TOTALES',
'initials': 'GT',
'type': 3,
'unit': 'BS',
'description': 'GASTOS TOTALES EN EL TIEMPO DE SIMULACIÓN'},

{'name': 'COSTO TOTAL TRANSPORTE',
'initials': 'CTTL',
'type': 3,
'unit': 'BS',
'description': 'COSTOS TOTALES EN EL TRANSPORTE DE INSUMOS Y PROUDTOS FINALES'},

{'name': 'COSTO PROMEDIO PRODUCCION',
'initials': 'CPP',
'type': 3,
'unit': 'BS',
'description': 'COSTOS PROMEDIO DE PRODUCCION POR PRODUCTO'},

{'name': 'COSTO PROMEDIO VENTA',
'initials': 'CPV',
'type': 3,
'unit': 'BS',
'description': 'COSTOS PROMEDIO DE VENTA POR PRODUCTO'},

{'name': 'COSTO PROMEDIO INSUMOS',
'initials': 'CPI',
'type': 3,
'unit': 'BS',
'description': 'COSTOS PROMEDIO DE VENTA POR PRODUCTO'},

{'name': 'Costo Promedio Mano Obra',
'initials': 'CPMO',
'type': 3,
'unit': 'BS',
'description': 'COSTOS PROMEDIO DE VENTA POR PRODUCTO'},

{'name': 'Costo Unitario Producción',
'initials': 'CUP',
'type': 3,
'unit': 'BS',
'description': 'Costo Unitario Producción'},

{'name': 'Precio Venta Recomendado',
'initials': 'PVR',
'type': 3,
'unit': 'BS',
'description': 'Precio Venta Recomendado'},

{'name': 'Factor Utilización',
'initials': 'FU',
'type': 3,
'unit': 'BS',
'description': 'Factor Utilización'},

{'name': 'Total Gastos',
'initials': 'TG',
'type': 3,
'unit': 'BS',
'description': 'Total Gastos'},

{'name': 'Ingreso Bruto',
'initials': 'IB',
'type': 3,
'unit': 'BS',
'description': 'Ingreso Bruto'},

{'name': 'Margen Bruto',
 'initials': 'MB',
 'type': 3,
 'unit': 'BS',
 'description': 'Margen Bruto - Indica la diferencia entre los ingresos totales y los costos directos de producción.'},

{'name': 'Retorno Inversión',
'initials': 'RI',
'type': 3,
'unit': 'BS',
'description': 'Retorno Inversión'},

{'name': 'Rotación Inventario',
'initials': 'RTI',
'type': 3,
'unit': 'L',
'description': 'Rotación Inventario'},

{'name': 'Rotación Clientes',
 'initials': 'RTC',
 'type': 3,
 'unit': 'BS',
 'description': 'Rotación de clientes - Indica la frecuencia con la que los clientes realizan compras en un período de tiempo determinado.'},

{'name': 'Participación Mercado',
 'initials': 'PM',
 'type': 3,
 'unit': '%',
 'description': 'Participación de mercado - Porcentaje de ventas de una empresa en relación con el total de ventas del mercado.'},

{'name': 'Productividad Empleados',
 'initials': 'PE',
 'type': 3,
 'unit': 'BS',
 'description': 'Productividad de empleados - Medida de la eficiencia y eficacia de los empleados en la producción o prestación de servicios.'},

{'name': 'Horas Ociosas',
 'initials': 'HO',
 'type': 3,
 'unit': 'Horas',
 'description': 'Horas ociosas - Tiempo en el que los empleados no están realizando ninguna actividad productiva.'},

{'name': 'Costo Horas Ociosas',
 'initials': 'CHO',
 'type': 3,
 'unit': 'BS',
 'description': 'Costo de horas ociosas - Costo asociado al tiempo en el que los empleados no están realizando ninguna actividad productiva.'},

{'name': 'Costo Almacenamiento',
 'initials': 'CA',
 'type': 3,
 'unit': 'BS',
 'description': 'Costo de almacenamiento - Costo asociado al almacenamiento de productos o materiales durante un período de tiempo determinado.'},

]
