variables_data = [
{'name': 'CANTIDAD DE PRODUCTOS QUE VENDE POR DIA',
'initials': 'CPVD',
'type': 1,
'unit': 'LITROS/DIAS',
'description': 'CANTIDAD DE LITROS DEL PRODUCTO QUE LA EMPRESA VENDE POR DIAS'},

{'name': 'PRECIO DE VENTA DEL PRODUCTO',
'initials': 'PVP',
'type': 1,
'unit': 'BS',
'description': 'PRECIO DE VENTA DEL PRODUCTO LÁCTEO'},

{'name': 'DEMANDA HISTÓRICA',
'initials': 'DH',
'type': 1,
'unit': 'LITROS',
'description': 'DATOS HISTÓRICOS DE DEMANDA DE LOS ÚLTIMOS UNIDADES DE TIEMPO'},

{'name': 'DEMANDA ESPERADA',
'initials': 'DE',
'type': 1,
'unit': 'LITROS/BS',
'description': 'DEMANDA ESPERADA EN EL PERIODO DE TIEMPO ESTABLECIDO'},

{'name': 'COSTO DE PRODUCCIÓN UNITARIO',
'initials': 'CPU',
'type': 1,
'unit': 'BS',
'description': 'COSTO UNITARIO POR LA PRODUCCIÓN'},

{'name': 'CAPACIDAD INVENTARIO PRODUCTOS',
'initials': 'CIP',
'type': 1,
'unit': 'LITROS',
'description': 'CAPACIDAD MÁXIMA QUE LA EMPRESA PUEDE ALMACENAR EN INVENTARIO'},

{'name': 'ESTACIONALIDAD DE LA DEMANDA',
'initials': 'ED',
'type': 1,
'unit': '[0-1]',
'description': 'VARIACIONES PREDECIBLES DE LA DEMANDA DE UN PRODUCTO O SERVICIO EN MOMENTOS ESPECÍFICOS DEL AÑO.'},

{'name': 'COSTO UNITARIO INSUMO PRODUCCIÓN',
'initials': 'CUIP',
'type': 1,
'unit': 'LITROS/BS',
'description': 'COSTO QUE LE CUESTA A LA EMPRESA POR INSUMO'},

{'name': 'NIVEL DE COMPETENCIA EN EL MERCADO',
'initials': 'NCM',
'type': 1,
'unit': '[0-1]',
'description': 'EL NIVEL QUE LA EMPRESA TIENE DE COMPETENCIA EN EL MERCADO'},

{'name': 'POSICIONAMIENTO DE LA EMPRESA',
'initials': 'PE',
'type': 1,
'unit': '[0-1]',
'description': 'Cuál ES EL POSICIONAMIENTO DE LA EMPRESA EN EL MERCADO'},

{'name': 'FRECUENCIA DE COMPRA',
'initials': 'FC',
'type': 1,
'unit': 'DIAS',
'description': 'CON QUÉ FRECUENCIA SUS CLIENTES COMPRAN PRODUCTOS DE SU EMPRESA'},

{'name': 'TASA DE RETENCIÓN CLIENTES',
'initials': 'TRC',
'type': 1,
'unit': '[0-1]',
'description': 'PORCENTAJE DE RETENCIÓN DE LOS CLIENTES QUE COMPRAN'},

{'name': 'SATISFACCIÓN DEL CLIENTE',
'initials': 'SC',
'type': 1,
'unit': '[0-1]',
'description': 'NIVEL DE SATISFACCIÓN DEL CLIENTE CON LOS PRODUCTOS'},

{'name': 'NIVEL LEALTAD DEL CLIENTE',
'initials': 'NLC',
'type': 1,
'unit': '[0-1]',
'description': 'NIVEL DE LEALTAD QUE TIENE EL CLIENTE CON LOS PRODUCTOS DE LA EMPRE'},

{'name': 'COSTO UNITARIO DE ADQUISICIÓN DE CLIENTES',
'initials': 'CUAC',
'type': 1,
'unit': 'CLIENTE/BS',
'description': 'EL GASTO PROMEDIO NECESARIO PARA CONSEGUIR QUE UN CLIENTE REALICE UNA COMPRA'},

{'name': 'COSTO UNITARIO DE RETENCIÓN DE CLIENTE',
'initials': 'CURC',
'type': 1,
'unit': 'CLIENTE/BS',
'description': 'EL GASTO PROMEDIO QUE UNA EMPRESA INCURRE PARA MANTENER A UN CLIENTE EXISTENTE DURANTE UN PERÍODO DETERMINADO'},

{'name': 'CLIENTES POR DÍA',
'initials': 'CPD',
'type': 1,
'unit': 'CLIENTE/BS',
'description': 'COSTO POR CLIENTE EN ATENCIÓN'},

{'name': 'NIVEL AUTOMATIZACIÓN DE PROCESO PRODUCCIÓN',
'initials': 'NAPP',
'type': 1,
'unit': '[0-1]',
'description': 'NIVEL DE AUTOMATIZACIÓN DE LOS PROCESOS DE PRODUCCIÓN DE LA EMPRESA'},

{'name': 'NIVEL EFICIENCIA EN EL PROCESO DE PRODUCCIÓN',
'initials': 'NEPP',
'type': 1,
'unit': '[0-1]',
'description': 'NIVEL DE EFICIENCIA EN EL PROCESO DE PRODUCCIÓN DE LOS PRODUCTOS'},

{'name': 'CERTIFICACION DE CALIDAD DEL PRODUCTO',
'initials': 'CERCAL',
'type': 1,
'unit': '[0-1]',
'description': 'CERTIFICACION DE CALIDAD DEL PRODUCTO'},

{'name': 'TIEMPO PRODUCCIÓN POR PRODUCTO',
'initials': 'TPP',
'type': 1,
'unit': 'MINUTOS',
'description': 'EL TIEMPO QUE SE TOMA LA EMPRESA POR LA PRODUCCIÓN DE UN PRODUCTO'},

{'name': 'CAPACIDAD DE PRODUCCIÓN',
'initials': 'CPROD',
'type': 2,
'unit': 'LITROS/DIAS',
'description': 'Capacidad de produccion'},

{'name': 'Artículos por lote de producción',
'initials': 'ALEP',
'type': 1,
'unit': 'UNIDADES',
'description': 'Artículos por lote de producción'},

{'name': 'Tiempo de produccion por empleado',
'initials': 'TE',
'type': 1,
'unit': 'DIAS',
'description': 'Tiempo de produccion por empleado'},

{'name': 'NIVEL FLEXIBILIDAD EN LA PRODUCCIÓN',
'initials': 'NFP',
'type': 1,
'unit': '[0.1,0.3,0.5]',
'description': 'NIVEL DE FLEXIBILIDAD DE LOS PROCESOS DE PRODUCCIÓN DE LA EMPRESA'},

{'name': 'NIVEL DE EFICIENCIA DE INVENTARIO',
'initials': 'NEI',
'type': 1,
'unit': '[0.1,0.3,0.5]',
'description': 'NIVEL DE EFICIENCIA EN EL MANEJO DE INVENTARIOS'},

{'name': 'NIVEL EFICIENCIA CADENA SUMINISTRO',
'initials': 'NECS',
'type': 1,
'unit': '[0.1,0.3,0.5]',
'description': 'NIVEL DE EFICIENCIA EN LA CADENA DE SUMINISTRO'},

{'name': 'NIVEL EFICIENCIA GESTIÓN DE COMPRA INSUMOS',
'initials': 'NEGCI',
'type': 1,
'unit': '[0.1,0.3,0.5]',
'description': 'NIVEL DE EFICIENCIA EN LA GESTIÓN DE COMPRA DE INSUMOS'},

{'name': 'NIVEL DE EFICIENCIA EN LA GESTIÓN DE VENTAS',
'initials': 'NEGV',
'type': 1,
'unit': '[0.1,0.3,0.5]',
'description': 'NIVEL DE EFICIENCIA EN LA GESTIÓN DE VENTAS'},

{'name': 'SUELDOS EMPLEADOS',
'initials': 'SE',
'type': 1,
'unit': 'BS',
'description': 'SUELDOS EMPLEADOS'},

{'name': 'PRECIO DE VENTA PROMEDIO DE LOS PRODUCTOS DE LA COMPETENCIA',
'initials': 'PVPCC',
'type': 1,
'unit': 'BS',
'description': 'PRECIO DE VENTA DEL MISMO PRODUCTO PERO DE LA COMPETENCIA'},

{'name': 'COSTO FIJO DIARIO',
'initials': 'CFD',
'type': 1,
'unit': 'BS',
'description': 'COSTO FIJO DIARIO DE LA EMPRESA'},

{'name': 'COSTO UNITARIO POR TRANSPORTE',
'initials': 'CUTRANS',
'type': 1,
'unit': 'LITROS/BS',
'description': 'COSTO UNITARIO POR TRANSPORTE DE UN BIEN FINAL DE LA FÁBRICA A LA TIENDA'},

{'name': 'COSTO UNITARIO INVENTARIO',
'initials': 'CUI',
'type': 1,
'unit': 'BS',
'description': 'EL COSTO POR UNIDAD DE MANTENER INVENTARIO, INCLUYENDO ALMACENAMIENTO, SEGUROS, DEPRECIACIÓN Y OPORTUNIDAD DE CAPITAL INMOVILIZADO.'},

{'name': 'GASTOS DE MARKETING MENSUAL',
'initials': 'GMM',
'type': 1,
'unit': 'LITROS/BS',
'description': 'CANTIDAD DE DINERO INVERTIDA EN ACTIVIDADES DE MARKETING DURANTE UN MES DETERMINADO PARA PROMOCIONAR PRODUCTOS O SERVICIOS.'},

{'name': 'TIEMPO REABASTECIMIENTO',
'initials': 'TR',
'type': 1,
'unit': 'DIAS',
'description': 'ES EL PERIODO NECESARIO PARA REPONER EL INVENTARIO DE UN PRODUCTO UNA VEZ AGOTADO.'},

{'name': 'CANTIDAD DE INSUMOS PARA UN PRODUCTO',
'initials': 'CIP',
'type': 1,
'unit': 'LITROS',
'description': 'CANTIDAD QUE LA EMPRESA UTILIZA PAR LA PRODUCCIÓN DE UN INSUMO'},

{'name': 'CAPACIDAD MÁXIMA INVENTARIO PRODUCTO FINAL',
'initials': 'CMIPF',
'type': 1,
'unit': 'LITROS',
'description': 'CAPACIDAD MAXIMA DE INSUMOS DEL PRODUCTO FINAL'},

{'name': 'NUMERO MAXIMO DE DIAS',
'initials': 'NMD',
'type': 1,
'unit': 'DIAS',
'description': 'CAPACIDAD MAXIMA DE INSUMOS DEL PRODUCTO FINAL'},

{'name': 'CONTADOR DIAS',
'initials': 'CD',
'type': 2,
'unit': 'DIAS',
'description': 'CONTADOR DE DIAS QUE PASAN'},

{'name': 'ALEATORIO LLEGADA DE CLIENTES',
'initials': 'ALC',
'type': 2,
'unit': '[0-1]',
'description': 'ALEATORIO PARA GENERAR EL NÚMERO DE CLIENTES'},

{'name': 'ALEATORIO VENTA',
'initials': 'AV',
'type': 2,
'unit': '[0-1]',
'description': 'CANTIDAD DE INSUMOS REQUERIDOS PARA LA PRODUCCIÓN DE BIENES O SERVICIOS, SUJETA A VARIACIONES ALEATORIAS EN EL SISTEMA.'},

{'name': 'INGRESO BRUTO',
'initials': 'IB',
'type': 2,
'unit': 'BS',
'description': 'TOTAL DE INGRESOS OBTENIDOS ANTES DE DEDUCIR LOS GASTOS Y LOS IMPUESTOS, MEDIDA FINANCIERA UTILIZADA PARA EVALUAR LA RENTABILIDAD.'},


{'name': 'LLEGADA DE CLIENTES',
'initials': 'LC',
'type': 2,
'unit': 'BS',
'description': 'FRECUENCIA CON LA QUE LOS CLIENTES LLEGAN A UN ESTABLECIMIENTO O NEGOCIO'},

{'name': 'INVENTARIO INSUMOS',
'initials': 'II',
'type': 2,
'unit': 'LITROS',
'description': 'CANTIDAD DE INSUMOS EXISTENTES EN INVENTARIO'},

{'name': 'INVENTARIO PRODUCTOS FINALES',
'initials': 'IPF',
'type': 2,
'unit': 'LITROS',
'description': 'CANTIDAD DE INSUMOS QUE SE USA AL REALIZAR UNA VENTA'},

{'name': 'PEDIDO INSUMOS',
'initials': 'PI',
'type': 2,
'unit': 'LITROS',
'description': 'CANTIDAD DE VÍVERES QUE SE PIDEN AL REORDENAR PARA EL REABASTECIMIENTO DE INVENTARIO'},

{'name': 'TOTAL CLIENTES ATENDIDOS EN EL DIAS',
'initials': 'TCAE',
'type': 2,
'unit': 'CLIENTES',
'description': 'NÚMERO TOTAL DE CLIENTES QUE FUERON ATENDIDOS'},

{'name': 'USO DE INVENTARIO INSUMOS',
'initials': 'UII',
'type': 2,
'unit': 'LITROS',
'description': 'AUXILIAR CANTIDAD DE INSUMOS QUE SE USA AL REALIZAR UNA VENTA'},

{'name': 'ALEATORIO EXITO PRODUCCIÓN',
'initials': 'AEP',
'type': 2,
'unit': '[0-1]',
'description': 'ALEATORIO PARA GENERAR EL NÚMERO DE CLIENTES'},

{'name': 'PRODUCTOS PRODUCIDOS',
'initials': 'PP',
'type': 2,
'unit': 'LITROS',
'description': 'CANTIDAD TOTAL DE PRODUCTOS LÁCTEOS FABRICADOS'},

{'name': 'COSTO TOTAL REORDEN',
'initials': 'CTR',
'type': 3,
'unit': 'LITROS/BS',
'description': 'EL COSTO TOTAL DE REALIZAR UN NUEVO PEDIDO DE INVENTARIO, INCLUYENDO EL COSTO DE ADQUISICIÓN, TRANSPORTE Y ALMACENAMIENTO.'},

{'name': 'COSTO TOTAL ADQUISICIÓN INSUMOS',
'initials': 'CTAI',
'type': 3,
'unit': 'BS',
'description': 'GASTO TOTAL EN LA ADQUISICIÓN DE INSUMOS UTILIZADOS EN LA PRODUCCIÓN'},

{'name': 'TOTAL PRODUCTOS VENDIDOS',
'initials': 'TPV',
'type': 3,
'unit': 'LITROS',
'description': 'CANTIDAD TOTAL DE PRODUCTOS VENDIDOS DE LA EMPRESA DURANTE UN PERIODO DETERMINADO'},

{'name': 'TOTAL PRODUCTOS PRODUCIDOS',
'initials': 'TPPRO',
'type': 3,
'unit': 'LITROS',
'description': 'CANTIDAD TOTAL DE PRODUCTOS PRODUCIDOS DE LA EMPRESA DURANTE UN PERIODO DETERMINADO'},

{'name': 'DEMANDA INSATISFECHA',
'initials': 'DI',
'type': 3,
'unit': 'LITROS',
'description': 'CANTIDAD DE PRODUCTOS QUE NO ESTUVIERON DISPONIBLES PARA LA VENTA'},

{'name': 'VENTAS POR CLIENTE',
'initials': 'VPC',
'type': 3,
'unit': 'LITROS',
'description': 'CANTIDAD DE PRODUCTOS VENDIDOS EN EL SECTOR LÁCTEO, VARIABLE UTILIZADA PARA LA TOMA DE DECISIONES FINANCIERAS EN LA PLATAFORMA WEB.'},

{'name': 'INGRESOS TOTALES',
'initials': 'IT',
'type': 3,
'unit': 'BS',
'description': 'CANTIDAD TOTAL DE INGRESOS GENERADOS POR LAS PYMES DEL SECTOR LÁCTEO, UTILIZADA EN LA TOMA DE DECISIONES FINANCIERAS EN LA PLATAFORMA WEB.'},

{'name': 'GANANCIAS TOTALES',
'initials': 'GT',
'type': 3,
'unit': 'BS',
'description': 'MONTO TOTAL DE GANANCIAS GENERADAS POR LAS PYMES DEL SECTOR LÁCTEO, UTILIZADA EN LA TOMA DE DECISIONES FINANCIERAS EN EL SISTEMA WEB.'},

{'name': 'TOTAL CLIENTES ATENDIDOS',
'initials': 'TCA',
'type': 3,
'unit': 'CLIENTES',
'description': 'GANANCIAS GENERADAS POR LAS PYMES LÁCTEAS, RESULTADO DE LA DIFERENCIA ENTRE INGRESOS Y COSTOS, UTILIZADAS PARA LA TOMA DE DECISIONES FINANCIERAS EN EL SISTEMA WEB.'},

{'name': 'NIVEL DE RENTABILIDAD',
'initials': 'NR',
'type': 3,
'unit': '[0.1,0.3,0.5]',
'description': 'NIVEL DE RENTABILIDAD DE LA EMPRESA'},

{'name': 'GASTOS OPERATIVOS',
'initials': 'GO',
'type': 3,
'unit': 'BS',
'description': 'COSTOS NECESARIOS PARA EL FUNCIONAMIENTO DIARIO DE LAS PYMES DEL SECTOR LÁCTEO, VARIABLE RELEVANTE EN LA TOMA DE DECISIONES FINANCIERAS.'},

{'name': 'GASTOS GENERALES',
'initials': 'GG',
'type': 3,
'unit': 'BS',
'description': 'COSTOS OPERATIVOS Y ADMINISTRATIVOS EN LAS PYMES DEL SECTOR LÁ'
},

{'name': 'GASTOS TOTALES',
'initials': 'GT',
'type': 3,
'unit': 'BS',
'description': 'GASTOS TOTALES EN EL TIEMPO DE SIMULACIÓN'},

{'name': 'COSTO TOTAL TRANSPORTE',
'initials': 'CTT',
'type': 3,
'unit': 'BS',
'description': 'COSTOS TOTALES EN EL TRANSPORTE DE INSUMOS Y PROUDTOS FINALES'},

{'name': 'COSTO PROMEDIO PRODUCCION',
'initials': 'CPP',
'type': 3,
'unit': 'BS',
'description': 'COSTOS PROMEDIO DE PRODUCCION POR PRODUCTO'},

{'name': 'COSTO PROMEDIO VENTA',
'initials': 'CPV',
'type': 3,
'unit': 'BS',
'description': 'COSTOS PROMEDIO DE VENTA POR PRODUCTO'},

{'name': 'COSTO PROMEDIO INSUMOS',
'initials': 'CPI',
'type': 3,
'unit': 'BS',
'description': 'COSTOS PROMEDIO DE VENTA POR PRODUCTO'},

{'name': 'Costo Promedio Mano Obra',
'initials': 'CPMO',
'type': 3,
'unit': 'BS',
'description': 'COSTOS PROMEDIO DE VENTA POR PRODUCTO'},

{'name': 'Costo Unitario Producción',
'initials': 'CUP',
'type': 3,
'unit': 'BS',
'description': 'Costo Unitario Producción'},

{'name': 'Precio Venta Recomendado',
'initials': 'PVR',
'type': 3,
'unit': 'BS',
'description': 'Precio Venta Recomendado'},

{'name': 'Factor Utilización',
'initials': 'FU',
'type': 3,
'unit': 'BS',
'description': 'Factor Utilización'},

{'name': 'Total Gastos',
'initials': 'TG',
'type': 3,
'unit': 'BS',
'description': 'Total Gastos'},

{'name': 'Ingreso Bruto',
'initials': 'IB',
'type': 3,
'unit': 'BS',
'description': 'Ingreso Bruto'},

{'name': 'Margen Bruto',
 'initials': 'MB',
 'type': 3,
 'unit': 'BS',
 'description': 'Margen Bruto - Indica la diferencia entre los ingresos totales y los costos directos de producción.'},

{'name': 'Retorno Inversión',
'initials': 'RI',
'type': 3,
'unit': 'BS',
'description': 'Retorno Inversión'},

{'name': 'Rotación Inventario',
'initials': 'RTI',
'type': 3,
'unit': 'LITROS',
'description': 'Rotación Inventario'},

{'name': 'Rotación Clientes',
 'initials': 'RTC',
 'type': 3,
 'unit': 'BS',
 'description': 'Rotación de clientes - Indica la frecuencia con la que los clientes realizan compras en un período de tiempo determinado.'},

{'name': 'Participación Mercado',
 'initials': 'PM',
 'type': 3,
 'unit': 'LITROS',
 'description': 'Participación de mercado - Porcentaje de ventas de una empresa en relación con el total de ventas del mercado.'},

{'name': 'Productividad Empleados',
 'initials': 'PE',
 'type': 3,
 'unit': 'BS',
 'description': 'Productividad de empleados - Medida de la eficiencia y eficacia de los empleados en la producción o prestación de servicios.'},

{'name': 'Horas Ociosas',
 'initials': 'HO',
 'type': 3,
 'unit': 'Horas',
 'description': 'Horas ociosas - Tiempo en el que los empleados no están realizando ninguna actividad productiva.'},

{'name': 'Costo Horas Ociosas',
 'initials': 'CHO',
 'type': 3,
 'unit': 'BS',
 'description': 'Costo de horas ociosas - Costo asociado al tiempo en el que los empleados no están realizando ninguna actividad productiva.'},

{'name': 'Costo Almacenamiento',
 'initials': 'CA',
 'type': 3,
 'unit': 'BS',
 'description': 'Costo de almacenamiento - Costo asociado al almacenamiento de productos o materiales durante un período de tiempo determinado.'},

]
