# Generated by Django 4.2.5 on 2023-11-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=70)),
                ('content', models.TextField(help_text='Detailed instructions content')),
                ('type', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the finance is active or not', verbose_name='Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date the finance was created', null=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now_add=True, help_text='The date the finance was created', null=True, verbose_name='Date Created')),
            ],
            options={
                'verbose_name_plural': 'Instructions',
            },
        ),
    ]
