# Generated by Django 4.2.7 on 2023-11-21 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(blank=True, help_text='Instruction', null=True)),
                ('content', models.TextField(blank=True, help_text='Detailed instructions content', null=True)),
                ('type', models.IntegerField(default=1, help_text='The type of the instruction')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the finance is active or not', verbose_name='Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date the finance was created', null=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now_add=True, help_text='The date the finance was created', null=True, verbose_name='Date Created')),
                ('fk_user', models.ForeignKey(default=1, help_text='The user associated with the instructions', on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_instructions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Instructions',
            },
        ),
    ]
