# Generated by Django 4.2.5 on 2023-11-19 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('layouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructions',
            name='fk_user',
            field=models.ForeignKey(default=1, help_text='The user associated with the instructions', on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_instructions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='content',
            field=models.TextField(blank=True, help_text='Detailed instructions content', null=True),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='instruction',
            field=models.TextField(blank=True, help_text='Instruction', null=True),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='type',
            field=models.IntegerField(default=1, help_text='The type of the instruction'),
        ),
    ]
