# Generated by Django 4.2.5 on 2023-11-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_profile_picture_userprofile_image_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image_user',
            new_name='image_src',
        ),
    ]
