# Generated by Django 4.2.7 on 2025-05-25 23:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('auto', 'Automático')], default='light', max_length=20, verbose_name='Tema')),
                ('items_per_page', models.PositiveIntegerField(default=10, verbose_name='Elementos por página')),
                ('dashboard_layout', models.JSONField(blank=True, default=dict, verbose_name='Diseño del dashboard')),
                ('quick_actions', models.JSONField(blank=True, default=list, verbose_name='Acciones rápidas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Preferencias de usuario',
                'verbose_name_plural': 'Preferencias de usuarios',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Clave de sesión')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Inicio de sesión')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Última actividad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sesión activa')),
            ],
            options={
                'verbose_name': 'Sesión de usuario',
                'verbose_name_plural': 'Sesiones de usuarios',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Registro de actividad', 'verbose_name_plural': 'Registros de actividades'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Perfil de usuario', 'verbose_name_plural': 'Perfiles de usuarios'},
        ),
        migrations.AddField(
            model_name='activitylog',
            name='category',
            field=models.CharField(blank=True, help_text='Categoría de la actividad (auth, profile, admin, etc.)', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción', null=True, verbose_name='Dirección IP'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', help_text='Nivel de prioridad del evento', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Información del navegador/cliente', verbose_name='User Agent'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del usuario', null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github',
            field=models.URLField(blank=True, help_text='Perfil de GitHub', verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('pt', 'Português')], default='es', help_text='Idioma preferido para la interfaz', max_length=10, verbose_name='Idioma preferido'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Perfil de LinkedIn', verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notifications_email',
            field=models.BooleanField(default=True, help_text='Recibir notificaciones por correo electrónico', verbose_name='Notificaciones por email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notifications_push',
            field=models.BooleanField(default=True, help_text='Recibir notificaciones push en el navegador', verbose_name='Notificaciones push'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_profile',
            field=models.CharField(choices=[('public', 'Público'), ('private', 'Privado'), ('contacts', 'Solo contactos')], default='public', help_text='Nivel de privacidad del perfil', max_length=20, verbose_name='Privacidad del perfil'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='America/La_Paz', help_text='Zona horaria del usuario', max_length=50, verbose_name='Zona horaria'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, help_text='Sitio web personal o profesional', verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(help_text='Descripción de la acción realizada', max_length=255, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='details',
            field=models.TextField(blank=True, help_text='Detalles adicionales de la acción', null=True, verbose_name='Detalles'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Descripción personal del usuario (máximo 500 caracteres)', max_length=500, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, help_text='País de residencia', max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image_src',
            field=models.ImageField(blank=True, help_text='Imagen de perfil del usuario', null=True, upload_to='images/user/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagen de perfil'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, help_text='Estado o departamento de residencia', max_length=100, verbose_name='Estado/Departamento'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='Usuario asociado al perfil', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-timestamp'], name='user_activi_user_id_3d3597_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', '-timestamp'], name='user_activi_action_b14986_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['priority', '-timestamp'], name='user_activi_priorit_7d0566_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['category', '-timestamp'], name='user_activi_categor_8ea632_idx'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
