# Generated by Django 4.2.11 on 2025-06-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_userpreferences_usersession_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="user_agent",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Información del navegador/cliente",
                max_length=500,
                null=True,
                verbose_name="User Agent",
            ),
        ),
    ]
